import { StyleSheet } from 'react-native';
import { normalize } from '../../../../shared/hooks/useResponsive';

export const COLORS = {
  bg: '#0A0E13',
  surface: '#151B23',
  surfaceLight: 'rgba(255, 255, 255, 0.05)',
  surfaceAlpha: 'rgba(31, 41, 55, 0.5)',
  primary: '#FF9500',
  primaryDark: '#E68600',
  primaryAlpha: 'rgba(255, 149, 0, 0.3)',
  success: '#32D74B',
  warning: '#FF9F0A',
  error: '#FF4444',
  purple: '#9333EA',
  cyan: '#00d4ff',
  textPrimary: '#F9FAFB',
  textSecondary: '#9CA3AF',
  textTertiary: '#6B7280',
  textMuted: '#4B5563',
  border: 'rgba(255, 255, 255, 0.08)',
  borderLight: 'rgba(255, 255, 255, 0.05)',
  overlayDark: 'rgba(0, 0, 0, 0.8)',
  transparent: 'transparent',
};

const styles = StyleSheet.create({
  exerciseItemContainer: {
    paddingTop: normalize(12),
    paddingHorizontal: normalize(10),
    position: 'relative',
    alignSelf: 'stretch',
    overflow: 'visible',
    backgroundColor: COLORS.bg,
  },
  exerciseCard: {
    backgroundColor: COLORS.surfaceAlpha,
    borderRadius: normalize(12),
    paddingHorizontal: normalize(16),
    paddingTop: normalize(12),
    paddingBottom: normalize(4),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  cardExpanded: {
    paddingBottom: normalize(16),
  },
  exerciseHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: normalize(8),
  },
  exerciseHeaderButton: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
  },
  imageContainer: {
    marginRight: normalize(10),
    padding: normalize(4),
    backgroundColor: COLORS.surfaceLight,
    borderRadius: normalize(12),
  },
  exerciseImage: {
    width: normalize(40),
    height: normalize(40),
    marginTop: normalize(4),
    borderRadius: normalize(12),
  },
  exerciseTextContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
  },
  nameAndSetsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: normalize(4),
  },
  exerciseName: {
    fontSize: normalize(14),
    fontWeight: '700',
    color: COLORS.textPrimary,
    flex: 1,
  },
  setsRepsSummary: {
    fontSize: normalize(14),
    fontWeight: '600',
    marginTop: normalize(2),
    color: COLORS.textTertiary,
    flexDirection: 'row',
    alignItems: 'center',
  },
  setsRepsText: {
    fontSize: normalize(14),
    fontWeight: '600',
    color: COLORS.textTertiary,
  },
  circleSeparator: {
    width: normalize(4),
    height: normalize(4),
    borderRadius: normalize(2),
    backgroundColor: COLORS.textTertiary,
    marginHorizontal: normalize(6),
  },
  headerButtonsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
  },
  collapseButton: {
    width: normalize(32),
    height: normalize(32),
    borderRadius: normalize(16),
    backgroundColor: COLORS.surfaceLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  detailsContainer: {
    paddingTop: normalize(16),
    borderTopWidth: 1,
    borderTopColor: COLORS.borderLight,
    overflow: 'hidden',
  },
  detailsContainerPadding: {
    paddingBottom: normalize(8),
  },
  detailRow: {
    marginBottom: normalize(16),
  },
  detailLabel: {
    fontSize: normalize(12),
    fontWeight: '600',
    color: COLORS.textSecondary,
    marginBottom: normalize(6),
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  chipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: normalize(8),
    marginBottom: normalize(-8),
  },
  chip: {
    backgroundColor: COLORS.surfaceLight,
    borderRadius: normalize(20),
    paddingVertical: normalize(5),
    paddingHorizontal: normalize(10),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  selectedChip: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  chipText: {
    fontSize: normalize(12),
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  selectedChipText: {
    color: COLORS.bg,
  },
  noteContainer: {
    flexDirection: 'column',
  },
  noteRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  noteTextInput: {
    flex: 1,
    backgroundColor: COLORS.surfaceLight,
    borderRadius: normalize(12),
    padding: normalize(12),
    fontSize: normalize(14),
    color: COLORS.textPrimary,
    borderWidth: 1,
    borderColor: COLORS.border,
    minHeight: normalize(80),
    maxHeight: normalize(80),
    textAlignVertical: 'top',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.overlayDark,
    padding: normalize(20),
  },
  modalContent: {
    backgroundColor: COLORS.surface,
    borderRadius: normalize(16),
    padding: normalize(24),
    width: '100%',
    maxWidth: normalize(380),
  },
  modalTitle: {
    fontSize: normalize(20),
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginBottom: normalize(24),
    textAlign: 'center',
  },
  modalInput: {
    backgroundColor: COLORS.surfaceLight,
    borderRadius: normalize(12),
    padding: normalize(14),
    fontSize: normalize(15),
    color: COLORS.textPrimary,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: normalize(20),
  },
  timeInputsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: normalize(24),
  },
  timeInputGroup: {
    alignItems: 'center',
  },
  timeInput: {
    backgroundColor: COLORS.surfaceLight,
    borderRadius: normalize(12),
    padding: normalize(16),
    fontSize: normalize(32),
    fontWeight: '700',
    color: COLORS.textPrimary,
    borderWidth: 1,
    borderColor: COLORS.border,
    width: normalize(80),
    textAlign: 'center',
  },
  timeLabel: {
    fontSize: normalize(12),
    fontWeight: '600',
    color: COLORS.textSecondary,
    marginTop: normalize(8),
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  timeSeparator: {
    fontSize: normalize(32),
    fontWeight: '700',
    color: COLORS.textSecondary,
    marginHorizontal: normalize(12),
    marginBottom: normalize(20),
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: normalize(8),
  },
  modalButton: {
    flex: 1,
    padding: normalize(14),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: normalize(12),
    backgroundColor: COLORS.surfaceLight,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  primaryButton: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  buttonText: {
    fontSize: normalize(15),
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  primaryButtonText: {
    color: COLORS.bg,
  },
  swipeBackground: {
    position: 'absolute',
    top: normalize(12),
    left: normalize(10),
    right: normalize(10),
    bottom: normalize(4),
    borderRadius: normalize(12),
  },
  setsAndRestRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  setsSection: {
    flex: 1,
    marginRight: normalize(10),
  },
  restSection: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  inlineRestSelector: {
    alignSelf: 'center',
    position: 'relative',
    zIndex: 1000,
  },
  restSelectorBackdrop: {
    position: 'absolute',
    top: -1000,
    left: -1000,
    right: -1000,
    bottom: -1000,
    backgroundColor: COLORS.transparent,
    zIndex: 999,
  },
  restTimeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: normalize(55),
    height: normalize(24),
    borderRadius: normalize(12),
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surfaceLight,
  },
  restTimeChipText: {
    fontSize: normalize(12),
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  expandedRestOptions: {
    position: 'absolute',
    top: normalize(32),
    right: 0,
    zIndex: 1000,
    transformOrigin: 'top',
    marginTop: normalize(8),
    padding: normalize(8),
    backgroundColor: COLORS.surface,
    borderRadius: normalize(12),
    borderWidth: 1,
    borderColor: COLORS.primaryAlpha,
    shadowColor: COLORS.bg,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
    width: normalize(110),
  },
  restOptionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: normalize(6),
    marginBottom: normalize(8),
  },
  restOptionChip: {
    paddingVertical: normalize(4),
    paddingHorizontal: normalize(10),
    borderRadius: normalize(10),
    backgroundColor: COLORS.surfaceLight,
    borderWidth: 1,
    borderColor: COLORS.border,
    minWidth: normalize(40),
    alignItems: 'center',
  },
  restOptionText: {
    fontSize: normalize(11),
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  restActionsRow: {
    flexDirection: 'row',
    gap: normalize(6),
    paddingTop: normalize(4),
    borderTopWidth: 1,
    borderTopColor: COLORS.borderLight,
  },
  restActionChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: normalize(4),
    paddingHorizontal: normalize(8),
    borderRadius: normalize(10),
    backgroundColor: COLORS.surfaceLight,
    borderWidth: 1,
    borderColor: COLORS.border,
    minHeight: normalize(26),
  },
  restActionText: {
    fontSize: normalize(10),
    fontWeight: '600',
    color: COLORS.textTertiary,
  },
  actionIcon: {
    marginRight: normalize(4),
  },
});

export default styles;