import { StyleSheet } from 'react-native';
import { normalize } from '../../../../shared/hooks/useResponsive';

// Updated color palette
export const COLORS = {
  primary: '#ff8535',
  primaryDark: '#F17C12',
  primaryLight: '#FFBC7D',
  primaryTransparent: 'rgba(255, 159, 67, 0.15)',
  secondary: '#1E293B',
  accent: '#FFFFFF',
  accent2: '#06B6D4',
  accent2Transparent: 'rgba(6, 182, 212, 0.15)',
  accent2Border: 'rgba(6, 182, 212, 0.5)',
  background: '#02111B',
  card: 'rgba(30, 41, 59, 0.9)',
  cardAlt: 'rgba(30, 41, 59, 0.5)',
  text: '#FFFFFF',
  textSecondary: '#A0AEC0',
  textMuted: 'rgba(160, 174, 192, 0.7)',
  border: 'rgba(255,255,255,0.15)',
  borderVariations: [
    'rgba(255, 159, 67, 0.3)',
    'rgba(6, 182, 212, 0.3)',
    'rgba(59, 130, 246, 0.3)',
  ],
  divider: 'rgba(255,255,255,0.08)',
  error: '#F6506C',
  errorMuted: 'rgba(246, 80, 108, 0.3)',
  success: '#34D399',
  warning: '#FF9F43',
  info: '#3D9AF1',
  disabled: '#4B5E6F',
  gradient: {
    primary: ['#FF9F43', '#F17C12'],
    button: ['#FF9F43', '#FFBC7D'],
    nav: ['rgba(30, 41, 59, 0.8)', 'rgba(2, 17, 27, 0.9)'],
    border: ['rgba(255, 159, 67, 0.5)', 'rgba(6, 182, 212, 0.5)'],
  },
};

const styles = StyleSheet.create({
  exerciseItemContainer: {
    paddingTop: normalize(12),
    paddingHorizontal: normalize(10),
    position: 'relative',
    alignSelf: 'stretch',
    overflow: 'visible',
    backgroundColor: COLORS.background,
  },
  exerciseCard: {
    backgroundColor: COLORS.cardAlt,
    borderRadius: normalize(12),
    paddingHorizontal: normalize(16),
    paddingTop: normalize(12),
    paddingBottom: normalize(4),
  },
  cardExpanded: {
    paddingBottom: normalize(16),
  },
  exerciseHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: normalize(8),
  },
  exerciseHeaderButton: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
  },
  imageContainer: {
    marginRight: normalize(10),
    padding: normalize(4),
    backgroundColor: COLORS.card,
    borderRadius: normalize(12),
  },
  exerciseImage: {
    width: normalize(40),
    height: normalize(40),
    marginTop: normalize(4),
    borderRadius: normalize(12),
  },
  exerciseTextContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
  },
  nameAndSetsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: normalize(4),
  },
  exerciseName: {
    fontSize: normalize(14),
    fontWeight: '700',
    color: COLORS.text,
    flex: 1,
  },
  setsRepsSummary: {
    fontSize: normalize(14),
    fontWeight: '600',
    marginTop: normalize(2),
    color: COLORS.textMuted,
    flexDirection: 'row',
    alignItems: 'center',
  },
  setsRepsText: {
    fontSize: normalize(14),
    fontWeight: '600',
    color: COLORS.textMuted,
  },
  circleSeparator: {
    width: normalize(4),
    height: normalize(4),
    borderRadius: normalize(2),
    backgroundColor: COLORS.textMuted,
    marginHorizontal: normalize(6),
  },
  headerButtonsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
  },
  collapseButton: {
    width: normalize(32),
    height: normalize(32),
    borderRadius: normalize(16),
    backgroundColor: COLORS.accent2Border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  detailsContainer: {
    paddingTop: normalize(16),
    borderTopWidth: 1,
    borderTopColor: COLORS.divider,
    overflow: 'hidden',
  },
  detailsContainerPadding: {
    paddingBottom: normalize(8),
  },
  detailRow: {
    marginBottom: normalize(16),
  },
  detailLabel: {
    fontSize: normalize(12),
    fontWeight: '600',
    color: COLORS.textSecondary,
    marginBottom: normalize(6),
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  chipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: normalize(8),
    marginBottom: normalize(-8),
  },
  chip: {
    backgroundColor: 'rgba(20, 30, 45, 0.6)',
    borderRadius: normalize(20),
    paddingVertical: normalize(5),
    paddingHorizontal: normalize(10),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  selectedChip: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  chipText: {
    fontSize: normalize(12),
    fontWeight: '600',
    color: COLORS.text,
  },
  selectedChipText: {
    color: COLORS.secondary,
  },
  smallChip: {
    paddingVertical: normalize(4),
    paddingHorizontal: normalize(8),
  },
  smallChipText: {
    fontSize: normalize(10),
  },
  noteContainer: {
    flexDirection: 'column',
  },
  noteRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  noteTextInput: {
    flex: 1,
    backgroundColor: COLORS.card,
    borderRadius: normalize(12),
    padding: normalize(12),
    fontSize: normalize(14),
    color: COLORS.text,
    borderWidth: 0.5,
    borderColor: COLORS.border,
    minHeight: normalize(80),
    maxHeight: normalize(80),
    textAlignVertical: 'top',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    padding: normalize(20),
  },
  modalContent: {
    backgroundColor: COLORS.card,
    borderRadius: normalize(16),
    padding: normalize(24),
    width: '100%',
    maxWidth: normalize(380),
  },
  modalTitle: {
    fontSize: normalize(20),
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: normalize(24),
    textAlign: 'center',
  },
  modalInput: {
    backgroundColor: COLORS.cardAlt,
    borderRadius: normalize(12),
    padding: normalize(14),
    fontSize: normalize(15),
    color: COLORS.text,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: normalize(20),
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: normalize(8),
  },
  modalButton: {
    flex: 1,
    padding: normalize(14),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: normalize(12),
    backgroundColor: COLORS.cardAlt,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  primaryButton: {
    backgroundColor: COLORS.gradient.button[0],
    borderColor: COLORS.primary,
  },
  buttonText: {
    fontSize: normalize(15),
    fontWeight: '600',
    color: COLORS.text,
  },
  primaryButtonText: {
    color: COLORS.secondary,
  },
  swipeBackground: {
    position: 'absolute',
    top: normalize(12),
    left: normalize(10),
    right: normalize(10),
    bottom: normalize(4),
    borderRadius: normalize(12),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  leftActionContainer: {
    width: normalize(80),
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: normalize(8),
  },
  rightActionContainer: {
    width: normalize(80),
    justifyContent: 'center',
    alignItems: 'center',
    paddingRight: normalize(8),
  },
  swipeActionButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: normalize(64),
    borderRadius: normalize(12),
    marginVertical: normalize(4),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  swipeActionLeft: {
    marginLeft: normalize(8),
    marginRight: normalize(4),
  },
  swipeActionRight: {
    marginRight: normalize(8),
    marginLeft: normalize(4),
  },
  swipeActionText: {
    color: COLORS.accent,
    fontSize: normalize(10),
    fontWeight: '600',
    marginTop: normalize(2),
    textAlign: 'center',
  },
  setsAndRestRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  setsSection: {
    flex: 1,
    marginRight: normalize(10),
  },
  restSection: {
    flexDirection: 'column', // Changed to column to stack label and selector
    alignItems: 'center', // Center the label and selector horizontally
    justifyContent: 'flex-start',
  },
  inlineRestSelector: {
    alignSelf: 'center', // Ensure the selector itself is centered within restSection
    position: 'relative',
  },
  restTimeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: normalize(55),
    height: normalize(24),
    borderRadius: normalize(12),
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: 'rgba(20, 30, 45, 0.6)',
  },
  restTimeChipText: {
    fontSize: normalize(12),
    fontWeight: '600',
    color: COLORS.text,
  },
  expandedRestOptions: {
    marginTop: normalize(8),
    padding: normalize(8),
    backgroundColor: COLORS.card,
    borderRadius: normalize(12),
    borderWidth: 1,
    borderColor: COLORS.borderVariations[0],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
    width: normalize(110),
  },
  restOptionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: normalize(6),
    marginBottom: normalize(8),
  },
  restOptionChip: {
    paddingVertical: normalize(4),
    paddingHorizontal: normalize(10),
    borderRadius: normalize(10),
    backgroundColor: 'rgba(20, 30, 45, 0.6)',
    borderWidth: 1,
    borderColor: COLORS.border,
    minWidth: normalize(40),
    alignItems: 'center',
  },
  restOptionText: {
    fontSize: normalize(11),
    fontWeight: '600',
    color: COLORS.text,
  },
  restActionsRow: {
    flexDirection: 'row',
    gap: normalize(6),
    paddingTop: normalize(4),
    borderTopWidth: 1,
    borderTopColor: COLORS.divider,
  },
  restActionChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: normalize(4),
    paddingHorizontal: normalize(8),
    borderRadius: normalize(10),
    backgroundColor: 'rgba(20, 30, 45, 0.6)',
    borderWidth: 1,
    borderColor: COLORS.border,
    minHeight: normalize(26),
  },
  restActionText: {
    fontSize: normalize(10),
    fontWeight: '600',
    color: COLORS.textMuted,
  },
  actionIcon: {
    marginRight: normalize(4),
  },
});

export default styles;