import { colors, spacing, fontSize, fontWeight, radius } from '../../../../shared/theme';
import { createStyles } from '../../../../shared/theme/createStyles';

export const COLORS = {
    bg: colors.background.primary,
    surface: colors.background.secondary,
    surfaceLight: colors.faded.surface,
    surfaceAlpha: colors.background.secondary,
    primary: colors.accent.primary,
    primaryDark: colors.accent.primaryDark,
    primaryAlpha: colors.border.primary,
    success: colors.accent.successAlt,
    error: colors.accent.error,
    textPrimary: colors.text.primary,
    textSecondary: colors.text.secondary,
    textTertiary: colors.text.tertiary,
    textMuted: colors.text.quaternary,
    border: colors.border.default,
    borderLight: colors.border.light,
    overlayDark: 'rgba(0, 0, 0, 0.8)',
    transparent: 'transparent',
    secondary: colors.accent.buttonText,
};

const styles = createStyles(() => ({
    exerciseItemContainer: {
        paddingTop: spacing[2],
        paddingHorizontal: spacing[3],
        position: 'relative',
        alignSelf: 'stretch',
        overflow: 'visible',
        backgroundColor: colors.background.primary,
    },
    exerciseCard: {
        backgroundColor: colors.background.secondary,
        borderRadius: radius[3],
        paddingHorizontal: spacing[3],
        paddingTop: spacing[2],
        paddingBottom: spacing[1],
        borderWidth: 1,
        borderColor: colors.border.default,
    },
    cardExpanded: {
        paddingBottom: spacing[4],
    },
    exerciseHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing[2],
    },
    exerciseHeaderButton: {
        flexDirection: 'row',
        flex: 1,
        alignItems: 'center',
    },
    imageContainer: {
        marginRight: spacing[2],
        backgroundColor: colors.faded.surfaceLight,
        borderRadius: radius[2],
        borderWidth: 1,
        borderColor: colors.border.light,
        overflow: 'hidden',
        padding: spacing[1],
    },
    exerciseImage: {
        width: spacing[10],
        height: spacing[10],
        borderRadius: radius[2],
    },
    exerciseTextContainer: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
    },
    nameAndSetsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 2,
    },
    exerciseName: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.semibold,
        color: colors.text.primary,
        flex: 1,
    },
    setsRepsSummary: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    setsRepsText: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.medium,
        color: colors.text.tertiary,
    },
    circleSeparator: {
        width: 4,
        height: 4,
        borderRadius: 2,
        backgroundColor: colors.text.quaternary,
        marginHorizontal: spacing[1],
    },
    headerButtonsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing[2],
    },
    collapseButton: {
        width: spacing[8],
        height: spacing[8],
        borderRadius: radius[4],
        backgroundColor: colors.faded.surface,
        justifyContent: 'center',
        alignItems: 'center',
    },
    detailsContainer: {
        paddingTop: spacing[4],
        borderTopWidth: 1,
        borderTopColor: colors.border.light,
        overflow: 'hidden',
    },
    detailsContainerPadding: {
        paddingBottom: spacing[2],
    },
    detailRow: {
        marginBottom: spacing[4],
    },
    detailLabel: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.semibold,
        color: colors.text.secondary,
        marginBottom: spacing[1],
        letterSpacing: 0.8,
        textTransform: 'uppercase',
    },
    chipsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing[2],
    },
    chip: {
        backgroundColor: colors.faded.surface,
        borderRadius: radius[5],
        paddingVertical: spacing[1],
        paddingHorizontal: spacing[2],
        borderWidth: 1,
        borderColor: colors.border.default,
    },
    smallChip: {
        paddingVertical: 2,
        paddingHorizontal: spacing[2],
    },
    selectedChip: {
        backgroundColor: colors.accent.primary,
        borderColor: colors.accent.primary,
    },
    chipText: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.semibold,
        color: colors.text.primary,
    },
    smallChipText: {
        fontSize: fontSize[10],
    },
    selectedChipText: {
        color: colors.accent.buttonText,
    },
    noteContainer: {
        flexDirection: 'column',
    },
    noteRow: {
        flexDirection: 'row',
        alignItems: 'stretch',
    },
    noteTextInput: {
        flex: 1,
        backgroundColor: colors.faded.surface,
        borderRadius: radius[3],
        padding: spacing[3],
        fontSize: fontSize[14],
        color: colors.text.primary,
        borderWidth: 1,
        borderColor: colors.border.default,
        minHeight: 80,
        maxHeight: 80,
        textAlignVertical: 'top',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        padding: spacing[5],
    },
    modalContent: {
        backgroundColor: colors.background.secondary,
        borderRadius: radius[4],
        padding: spacing[6],
        width: '100%',
    },
    modalTitle: {
        fontSize: fontSize[20],
        fontWeight: fontWeight.bold,
        color: colors.text.primary,
        marginBottom: spacing[6],
        textAlign: 'center',
    },
    modalInput: {
        backgroundColor: colors.faded.surface,
        borderRadius: radius[3],
        padding: spacing[3],
        fontSize: fontSize[16],
        color: colors.text.primary,
        borderWidth: 1,
        borderColor: colors.border.default,
        marginBottom: spacing[5],
    },
    timeInputsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: spacing[6],
    },
    timeInputGroup: {
        alignItems: 'center',
    },
    timeInput: {
        backgroundColor: colors.faded.surface,
        borderRadius: radius[3],
        padding: spacing[4],
        fontSize: fontSize[32],
        fontWeight: fontWeight.bold,
        color: colors.text.primary,
        borderWidth: 1,
        borderColor: colors.border.default,
        width: spacing[20],
        textAlign: 'center',
    },
    timeLabel: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.semibold,
        color: colors.text.secondary,
        marginTop: spacing[2],
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    timeSeparator: {
        fontSize: fontSize[32],
        fontWeight: fontWeight.bold,
        color: colors.text.secondary,
        marginHorizontal: spacing[3],
        marginBottom: spacing[5],
    },
    modalButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: spacing[2],
    },
    modalButton: {
        flex: 1,
        padding: spacing[3],
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: radius[3],
        backgroundColor: colors.faded.surface,
        borderWidth: 1,
        borderColor: colors.border.default,
    },
    primaryButton: {
        backgroundColor: colors.accent.primary,
        borderColor: colors.accent.primary,
    },
    buttonText: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.semibold,
        color: colors.text.primary,
    },
    primaryButtonText: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.semibold,
        color: colors.accent.buttonText,
    },
    swipeBackground: {
        position: 'absolute',
        top: spacing[2],
        left: spacing[3],
        right: spacing[3],
        bottom: spacing[1],
        borderRadius: radius[3],
    },
    setsAndRestRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    setsSection: {
        flex: 1,
        marginRight: spacing[3],
    },
    restSection: {
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    inlineRestSelector: {
        alignSelf: 'center',
        position: 'relative',
        zIndex: 1000,
    },
    restSelectorBackdrop: {
        position: 'absolute',
        top: -1000,
        left: -1000,
        right: -1000,
        bottom: -1000,
        backgroundColor: 'transparent',
        zIndex: 999,
    },
    restTimeChip: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: spacing[14],
        height: spacing[6],
        borderRadius: radius[3],
        borderWidth: 1,
        borderColor: colors.border.default,
        backgroundColor: colors.faded.surface,
        paddingHorizontal: spacing[2],
    },
    restTimeChipText: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.semibold,
        color: colors.text.primary,
    },
    expandedRestOptions: {
        position: 'absolute',
        top: spacing[7],
        right: 0,
        zIndex: 1000,
        marginTop: spacing[2],
        padding: spacing[2],
        backgroundColor: colors.background.secondary,
        borderRadius: radius[3],
        borderWidth: 1,
        borderColor: colors.border.primary,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 3,
        width: spacing[28],
    },
    restOptionsRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing[1],
        marginBottom: spacing[2],
    },
    restOptionChip: {
        paddingVertical: spacing[1],
        paddingHorizontal: spacing[2],
        borderRadius: radius[2],
        backgroundColor: colors.faded.surface,
        borderWidth: 1,
        borderColor: colors.border.default,
        minWidth: spacing[10],
        alignItems: 'center',
    },
    restOptionText: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.semibold,
        color: colors.text.primary,
    },
    restActionsRow: {
        flexDirection: 'row',
        gap: spacing[1],
        paddingTop: spacing[1],
        borderTopWidth: 1,
        borderTopColor: colors.border.light,
    },
    restActionChip: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: spacing[1],
        paddingHorizontal: spacing[2],
        borderRadius: radius[2],
        backgroundColor: colors.faded.surface,
        borderWidth: 1,
        borderColor: colors.border.default,
    },
    restActionText: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.semibold,
        color: colors.text.quaternary,
    },
    actionIcon: {
        marginRight: spacing[1],
    },
    dragHandleButton: {
        width: spacing[8],
        height: spacing[8],
        borderRadius: radius[4],
        backgroundColor: colors.faded.surface,
        justifyContent: 'center',
        alignItems: 'center',
    },
    draggingCard: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 8,
        elevation: 10,
    },
}));

export default styles;