// src/features/workout/screens/CreateSplitScreen/steps/ReviewStepStyles.js
import { createStyles } from '../../../../../shared/theme/createStyles';
import { colors, spacing, fontSize, fontWeight, radius } from '../../../../../shared/theme';

const styles = createStyles(() => ({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  contentContainer: {
    paddingHorizontal: spacing[5],
    paddingTop: spacing[5],
    paddingBottom: spacing[8],
    gap: spacing[5],
  },
  headerCard: {
    backgroundColor: colors.background.tertiary,
    borderRadius: radius[6],
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border.default,
    shadowColor: 'rgba(0, 0, 0, 0.3)',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
  },
  gradientOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  headerContent: {
    padding: spacing[6],
    position: 'relative',
    zIndex: 1,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing[5],
  },
  titleSection: {
    flex: 1,
  },
  splitName: {
    fontSize: fontSize[28],
    fontWeight: fontWeight.black,
    color: colors.text.primary,
    letterSpacing: -0.6,
    lineHeight: fontSize[32],
  },
  splitType: {
    fontSize: fontSize[14],
    fontWeight: fontWeight.semibold,
    color: colors.text.secondary,
    marginTop: spacing[1],
    opacity: 0.8,
  },
  editButton: {
    width: spacing[12],
    height: spacing[12],
    borderRadius: radius[6],
    backgroundColor: colors.border.default,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  quickStats: {
    flexDirection: 'row',
    gap: spacing[3],
    flexWrap: 'wrap',
  },
  statPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.border.light,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    borderRadius: radius[5],
    gap: spacing[1],
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  statText: {
    fontSize: fontSize[12],
    fontWeight: fontWeight.semibold,
    color: colors.text.primary,
  },
  scheduleCard: {
    backgroundColor: colors.background.tertiary,
    borderRadius: radius[6],
    padding: spacing[5],
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  scheduleHeader: {
    marginBottom: spacing[4],
    alignItems: 'center',
  },
  scheduleTitle: {
    fontSize: fontSize[20],
    fontWeight: fontWeight.black,
    color: colors.text.primary,
    letterSpacing: -0.6,
    lineHeight: fontSize[24],
  },
  scheduleSubtitle: {
    fontSize: fontSize[12],
    color: colors.text.secondary,
    marginTop: spacing[1],
    opacity: 0.8,
  },
  dayPillsContainer: {
    marginBottom: spacing[5],
    justifyContent: 'center',
    alignItems: 'center',
  },
  dayPills: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: spacing[2],
  },
  dayPillWrapper: {
    borderRadius: radius[6],
  },
  dayPill: {
    width: spacing[11],
    height: spacing[11],
    borderRadius: radius[6],
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border.default,
    backgroundColor: colors.background.secondary,
  },
  dayPillActive: {
    backgroundColor: colors.faded.primary,
    borderColor: colors.accent.primary,
  },
  restDayPill: {
    backgroundColor: colors.faded.surfaceMedium,
    borderColor: colors.text.quaternary,
  },
  dayPillText: {
    fontSize: fontSize[14],
    fontWeight: fontWeight.bold,
    color: colors.text.tertiary,
  },
  dayPillTextActive: {
    color: colors.accent.primary,
  },
  dayPillTextRest: {
    color: colors.text.primary,
  },
  currentWorkoutCard: {
    backgroundColor: colors.faded.primary,
    borderRadius: radius[4],
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.accent.primary,
    marginBottom: spacing[5],
  },
  restDayCard: {
    backgroundColor: colors.faded.cyan,
    borderRadius: radius[4],
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.accent.cyan,
    marginBottom: spacing[5],
    alignItems: 'center',
  },
  currentWorkoutTitle: {
    fontSize: fontSize[18],
    fontWeight: fontWeight.bold,
    color: colors.accent.primary,
    marginBottom: spacing[3],
    textAlign: 'center',
  },
  restDayTitle: {
    fontSize: fontSize[18],
    fontWeight: fontWeight.bold,
    color: colors.accent.cyan,
    marginBottom: spacing[3],
    textAlign: 'center',
  },
  workoutMetrics: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: spacing[4],
    gap: spacing[3],
  },
  workoutMetric: {
    flex: 1,
    alignItems: 'center',
    gap: spacing[1],
  },
  workoutMetricText: {
    fontSize: fontSize[12],
    color: colors.text.secondary,
    fontWeight: fontWeight.medium,
    textAlign: 'center',
    lineHeight: fontSize[18],
  },
  restMetrics: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    gap: spacing[3],
  },
  restMetric: {
    flex: 1,
    alignItems: 'center',
    gap: spacing[1],
  },
  restMetricText: {
    fontSize: fontSize[12],
    color: colors.text.secondary,
    fontWeight: fontWeight.medium,
    textAlign: 'center',
    lineHeight: fontSize[18],
  },
  muscleGroupTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: spacing[1],
  },
  muscleTag: {
    backgroundColor: colors.border.default,
    paddingHorizontal: spacing[2],
    paddingVertical: spacing[1],
    borderRadius: radius[3],
  },
  muscleTagText: {
    fontSize: fontSize[10],
    color: colors.text.secondary,
    fontWeight: fontWeight.semibold,
  },
  summaryStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: spacing[4],
    borderTopWidth: 1,
    borderTopColor: colors.border.light,
    paddingHorizontal: spacing[5],
  },
  summaryStatItem: {
    alignItems: 'center',
  },
  summaryStatValue: {
    fontSize: fontSize[20],
    fontWeight: fontWeight.extrabold,
    color: colors.accent.cyan,
    letterSpacing: -0.5,
  },
  summaryStatLabel: {
    fontSize: fontSize[10],
    color: colors.text.quaternary,
    fontWeight: fontWeight.medium,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  volumeCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: radius[4],
    borderWidth: 1,
    borderColor: colors.border.default,
    padding: spacing[4],
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing[3],
  },
  cardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
  },
  cardIconBox: {
    width: spacing[8],
    height: spacing[8],
    borderRadius: radius[2],
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: {
    fontSize: fontSize[12],
    fontWeight: fontWeight.bold,
    color: colors.text.primary,
  },
  cardSubtext: {
    fontSize: fontSize[10],
    fontWeight: fontWeight.medium,
    marginBottom: spacing[3],
    color: colors.text.quaternary,
  },
  volumeList: {
    gap: spacing[2],
  },
  volumeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
  },
  volumeLabelWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[1],
    width: spacing[20],
  },
  volumeDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
  },
  volumeLabel: {
    flexShrink: 1,
    fontSize: fontSize[10],
    fontWeight: fontWeight.semibold,
    color: colors.text.secondary,
  },
  volumeBarTrack: {
    flex: 1,
    height: spacing[2],
    borderRadius: radius[1],
    overflow: 'hidden',
    backgroundColor: colors.faded.surface,
  },
  volumeBarFill: {
    height: '100%',
    borderRadius: radius[1],
    minWidth: 3,
  },
  volumeValue: {
    width: spacing[7],
    textAlign: 'right',
    fontSize: fontSize[10],
    fontWeight: fontWeight.semibold,
    color: colors.text.secondary,
  },
  volumeEmptyText: {
    fontSize: fontSize[12],
    color: colors.text.quaternary,
    fontWeight: fontWeight.medium,
  },
  coverageNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    marginTop: spacing[4],
    paddingTop: spacing[3],
    borderTopWidth: 1,
    borderTopColor: colors.border.light,
  },
  coverageNoteText: {
    flex: 1,
    fontSize: fontSize[11],
    fontWeight: fontWeight.medium,
    color: colors.text.tertiary,
  },
}));

export default styles;