import { StyleSheet, Dimensions } from 'react-native';
import { normalize } from '../../../../../shared/hooks/useResponsive';

const { width: screenWidth } = Dimensions.get('window');

export const COLORS = {
  background: '#02111B',
  cardBackground: 'rgba(30, 41, 59, 0.5)',
  cardBackgroundDark: 'rgba(15, 23, 42, 0.8)',
  gradientOverlay: 'rgba(255, 133, 53, 0.05)',
  textPrimary: '#FFFFFF',
  textSecondary: '#d1d5db',
  textInactive: 'rgba(255, 255, 255, 0.4)',
  textMuted: '#9ca3af',
  border: 'rgba(255, 255, 255, 0.1)',
  borderDivider: 'rgba(255, 255, 255, 0.08)',
  accentPrimary: '#ff8535',
  accentSecondary: '#00d4ff',
  accentPurple: '#a855f7',
  success: '#10b981',
  warning: '#facc15',
  error: '#ef4444',
  shadow: 'rgba(0, 0, 0, 0.3)',
  mutedOrange: 'rgba(255, 133, 53, 0.8)',
  mutedBlue: 'rgba(0, 212, 255, 0.7)',
  mutedPurple: 'rgba(168, 85, 247, 0.8)',
  mutedGreen: 'rgba(16, 185, 129, 0.8)',
  mutedYellow: 'rgba(245, 158, 11, 0.8)',
  mutedRed: 'rgba(239, 68, 68, 0.8)',
  mutedGray: 'rgba(107, 114, 128, 0.3)',
  workoutCardBg: 'rgba(255, 133, 53, 0.15)',
  restCardBg: 'rgba(0, 212, 255, 0.1)',
  pieChart1: '#F28C82',
  pieChart2: '#81D4FA',
  pieChart3: '#A5D6A7',
  pieChart4: '#CE93D8',
  pieChart5: '#FFCC80',
  pieChart6: '#80DEEA',
  pieChart7: '#F48FB1',
  pieChart8: '#BCAAA4',
  pieChart9: '#FFE082',
  pieChart10: '#C5E1A5',
  accentPrimaryFaded: 'rgba(255, 133, 53, 0.15)',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: normalize(20),
    paddingBottom: normalize(20),
    gap: normalize(16),
  },

  // --- Header Card ---
  headerCard: {
    backgroundColor: COLORS.cardBackgroundDark,
    borderRadius: normalize(24),
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    marginBottom: normalize(20),
    marginHorizontal: normalize(20),
  },
  gradientOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  headerContent: {
    padding: normalize(24),
    position: 'relative',
    zIndex: 1,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: normalize(20),
  },
  titleSection: {
    flex: 1,
  },
  splitName: {
    fontSize: normalize(28),
    fontWeight: '900',
    color: COLORS.textPrimary,
    letterSpacing: -0.6,
    lineHeight: normalize(32),
  },
  splitType: {
    fontSize: normalize(14),
    fontWeight: '600',
    color: COLORS.textSecondary,
    marginTop: normalize(4),
    opacity: 0.8,
  },
  editButton: {
    width: normalize(48),
    height: normalize(48),
    borderRadius: normalize(24),
    backgroundColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  quickStats: {
    flexDirection: 'row',
    gap: normalize(12),
    flexWrap: 'wrap',
  },
  statPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.borderDivider,
    paddingHorizontal: normalize(12),
    paddingVertical: normalize(8),
    borderRadius: normalize(20),
    gap: normalize(6),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  statText: {
    fontSize: normalize(12),
    fontWeight: '600',
    color: COLORS.textPrimary,
  },

  // --- Tab Navigation ---
  tabNavigation: {
    flexDirection: 'row',
    backgroundColor: COLORS.cardBackground,
    borderRadius: normalize(16),
    padding: normalize(4),
    marginBottom: normalize(20),
    marginHorizontal: normalize(20),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: normalize(12),
    paddingHorizontal: normalize(16),
    borderRadius: normalize(12),
    gap: normalize(8),
  },
  tabActive: {
    backgroundColor: COLORS.accentPrimaryFaded,
    borderWidth: 1,
    borderColor: 'rgba(255, 133, 53, 0.3)',
  },
  tabText: {
    fontSize: normalize(13),
    fontWeight: '600',
    color: COLORS.textMuted,
  },
  tabTextActive: {
    color: COLORS.accentPrimary,
    fontWeight: '700',
  },

  // --- Content Cards ---
  tabContent: {
    flex: 1,
    gap: normalize(20),
  },
  scoreCard: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: normalize(20),
    padding: normalize(20),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  scoreHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(20),
  },
  scoreTitle: {
    fontSize: normalize(18),
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  scoreValue: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  scoreNumber: {
    fontSize: normalize(32),
    fontWeight: '900',
    color: COLORS.accentPrimary,
    letterSpacing: -1,
  },
  scoreOutOf: {
    fontSize: normalize(16),
    fontWeight: '600',
    color: COLORS.textSecondary,
    marginLeft: normalize(2),
  },
  scoreBreakdown: {
    gap: normalize(12),
  },
  scoreItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: normalize(12),
    padding: normalize(12),
    gap: normalize(12),
  },
  scoreIcon: {
    width: normalize(32),
    height: normalize(32),
    borderRadius: normalize(16),
    alignItems: 'center',
    justifyContent: 'center',
  },
  scoreIconSuccess: { backgroundColor: COLORS.success },
  scoreIconWarning: { backgroundColor: COLORS.warning },
  scoreIconError: { backgroundColor: COLORS.error },
  scoreIconInfo: { backgroundColor: 'rgba(59, 130, 246, 0.15)' },
  scoreDetails: {
    flex: 1,
  },
  scoreItemTitle: {
    fontSize: normalize(14),
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginBottom: normalize(2),
  },
  scoreItemDesc: {
    fontSize: normalize(12),
    color: COLORS.textMuted,
  },
  scoreItemValue: {
    fontSize: normalize(16),
    fontWeight: '800',
    color: COLORS.textSecondary,
  },
  metricsGrid: {
    flexDirection: 'row',
    gap: normalize(8),
    marginHorizontal: normalize(4),
  },
  metricCard: {
    flex: 1,
    backgroundColor: COLORS.cardBackground,
    borderRadius: normalize(14),
    padding: normalize(14),
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: normalize(6),
    minHeight: normalize(85),
  },
  metricValue: {
    fontSize: normalize(20),
    fontWeight: '800',
    color: COLORS.textPrimary,
    letterSpacing: -0.3,
  },
  metricLabel: {
    fontSize: normalize(10),
    fontWeight: '600',
    color: COLORS.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    textAlign: 'center',
    lineHeight: normalize(12),
  },
  analysisCard: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: normalize(20),
    padding: normalize(20),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  cardTitle: {
    fontSize: normalize(18),
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginBottom: normalize(16),
  },
  pieChartContainer: {
    alignItems: 'center',
    marginBottom: normalize(4),
  },
  pieChartWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  muscleDistributionContainer: {
    marginTop: normalize(24),
  },
  breakdownTitle: {
    fontSize: normalize(15),
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginBottom: normalize(12),
  },
  muscleListScrollContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
    paddingHorizontal: normalize(4),
    paddingBottom: normalize(4),
  },
  muscleCardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: normalize(12),
    paddingVertical: normalize(8),
    backgroundColor: COLORS.cardBackground,
    borderRadius: normalize(20),
    borderWidth: 1,
    borderColor: COLORS.border,
    minHeight: normalize(40),
  },
  muscleCardItemSelected: {
    backgroundColor: COLORS.accentPrimaryFaded,
    borderColor: COLORS.accentPrimary,
  },
  muscleCardInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
  },
  muscleCardName: {
    fontSize: normalize(13),
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  muscleCardSets: {
    fontSize: normalize(12),
    fontWeight: '500',
    color: COLORS.textSecondary,
    marginLeft: 'auto',
  },
  muscleColorDot: {
    width: normalize(10),
    height: normalize(10),
    borderRadius: normalize(5),
    marginRight: normalize(5),
  },

  // --- Schedule Tab Styles (Updated) ---
  scheduleCard: {
    backgroundColor: COLORS.cardBackgroundDark,
    borderRadius: normalize(24),
    padding: normalize(20),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  scheduleHeader: {
    marginBottom: normalize(16),
    alignItems: 'center',
  },
  scheduleTitle: {
    fontSize: normalize(20),
    fontWeight: '900',
    color: COLORS.textPrimary,
    letterSpacing: -0.6,
    lineHeight: normalize(24),
  },
  scheduleSubtitle: {
    fontSize: normalize(12),
    color: COLORS.textSecondary,
    marginTop: normalize(4),
    opacity: 0.8,
  },
  dayPillsContainer: {
    marginBottom: normalize(20),
    justifyContent: 'center',
    alignItems: 'center',
  },
  dayPills: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: normalize(8),
  },
  dayPillWrapper: {
    borderRadius: normalize(25),
  },
  dayPill: {
    width: normalize(46),
    height: normalize(46),
    borderRadius: normalize(25),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.cardBackground,
  },
  // The active pill now uses accentPrimary for both its background and border
  dayPillActive: {
    backgroundColor: COLORS.accentPrimaryFaded,
    borderColor: COLORS.accentPrimary,
  },
  // The rest day pill uses a muted gray color
  restDayPill: {
    backgroundColor: COLORS.mutedGray,
    borderColor: COLORS.textMuted,
  },
  dayPillText: {
    fontSize: normalize(14),
    fontWeight: '700',
    color: COLORS.textInactive,
  },
  // The active text now uses accentPrimary to match the pill
  dayPillTextActive: {
    color: COLORS.accentPrimary,
  },
  // The rest day text is now bright white for better contrast
  dayPillTextRest: {
    color: COLORS.textPrimary,
  },

  currentWorkoutCard: {
    backgroundColor: COLORS.workoutCardBg,
    borderRadius: normalize(16),
    padding: normalize(16),
    borderWidth: 1,
    borderColor: COLORS.mutedOrange,
    marginBottom: normalize(20),
  },
  restDayCard: {
    backgroundColor: COLORS.restCardBg,
    borderRadius: normalize(16),
    padding: normalize(16),
    borderWidth: 1,
    borderColor: COLORS.mutedBlue,
    marginBottom: normalize(20),
    alignItems: 'center',
  },
  currentWorkoutTitle: {
    fontSize: normalize(18),
    fontWeight: '700',
    color: COLORS.accentPrimary,
    marginBottom: normalize(12),
    textAlign: 'center',
  },
  restDayTitle: {
    fontSize: normalize(18),
    fontWeight: '700',
    color: COLORS.accentSecondary,
    marginBottom: normalize(12),
    textAlign: 'center',
  },
  workoutMetrics: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: normalize(16),
    gap: normalize(12),
  },
  workoutMetric: {
    flex: 1,
    alignItems: 'center',
    gap: normalize(6),
  },
  workoutMetricText: {
    fontSize: normalize(12),
    color: COLORS.textSecondary,
    fontWeight: '500',
    textAlign: 'center',
    lineHeight: normalize(18),
  },
  restMetrics: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: normalize(16),
    gap: normalize(12),
  },
  restMetric: {
    flex: 1,
    alignItems: 'center',
    gap: normalize(6),
  },
  restMetricText: {
    fontSize: normalize(12),
    color: COLORS.textSecondary,
    fontWeight: '500',
    textAlign: 'center',
    lineHeight: normalize(18),
  },
  muscleGroupTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: normalize(6),
  },
  muscleTag: {
    backgroundColor: COLORS.border,
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(4),
    borderRadius: normalize(12),
  },
  muscleTagText: {
    fontSize: normalize(10),
    color: COLORS.textSecondary,
    fontWeight: '600',
  },
  restSuggestions: {
    marginTop: normalize(8),
    alignItems: 'center',
  },
  restSuggestionText: {
    fontSize: normalize(12),
    color: COLORS.textMuted,
    fontWeight: '500',
    textAlign: 'center',
    lineHeight: normalize(16),
  },
  summaryStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: normalize(16),
    borderTopWidth: 1,
    borderTopColor: COLORS.borderDivider,
    paddingHorizontal: normalize(20),
  },
  summaryStatItem: {
    alignItems: 'center',
  },
  summaryStatValue: {
    fontSize: normalize(20),
    fontWeight: '800',
    color: COLORS.accentSecondary,
    letterSpacing: -0.5,
  },
  summaryStatLabel: {
    fontSize: normalize(10),
    color: COLORS.textMuted,
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
});

export default styles;