import { StyleSheet } from 'react-native';
import { normalize } from '../../../../../shared/hooks/useResponsive';

const colors = {
  bg: '#0A0E13',
  surface: '#151B23',
  surfaceLight: '#1F2937',
  primary: '#FF9500',
  primaryDark: '#E68600',
  success: '#32D74B',
  warning: '#FF9F0A',
  purple: '#9333EA',
  cyan: '#00d4ff',
  textPrimary: '#F9FAFB',
  textSecondary: '#9CA3AF',
  textTertiary: '#6B7280',
  border: 'rgba(255, 255, 255, 0.08)',
  borderLight: 'rgba(255, 255, 255, 0.05)',
};

const COLORS = {
  background: colors.bg,
  cardBackground: colors.surface,
  cardBackgroundDark: colors.surfaceLight,
  textPrimary: colors.textPrimary,
  textSecondary: colors.textSecondary,
  textInactive: 'rgba(255, 255, 255, 0.4)',
  textMuted: colors.textTertiary,
  border: colors.border,
  borderDivider: colors.borderLight,
  accentPrimary: colors.primary,
  accentSecondary: colors.cyan,
  accentPurple: colors.purple,
  success: colors.success,
  shadow: 'rgba(0, 0, 0, 0.3)',
  accentPrimaryFaded: 'rgba(255, 149, 0, 0.15)',
  mutedGray: 'rgba(107, 114, 128, 0.3)',
};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContent: {
    paddingBottom: normalize(20),
  },
  fixedHeader: {
    paddingVertical: normalize(10),
  },
  scrollableContent: {
    flex: 1,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: normalize(20),
  },
  titleSection: {
    flex: 1,
  },
  title: {
    fontSize: normalize(20),
    fontWeight: '800',
    color: COLORS.textPrimary,
    letterSpacing: -0.5,
  },
  addWorkoutTextButton: {
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(6),
    alignItems: 'center',
    justifyContent: 'center',
  },
  addWorkoutText: {
    fontSize: normalize(15),
    fontWeight: '600',
    color: COLORS.accentPrimary,
    letterSpacing: -0.2,
  },
  dayPillsScrollView: {
    marginHorizontal: normalize(16),
    marginVertical: normalize(15),
  },
  dayPillsContainer: {
    paddingHorizontal: normalize(4),
  },
  dayPills: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
  },
  dayPill: {
    paddingHorizontal: normalize(12),
    paddingVertical: normalize(10),
    borderRadius: normalize(12),
    alignItems: 'center',
    backgroundColor: 'transparent',
    minWidth: normalize(32),
  },
  dayPillWeekly: {
    flex: 1,
    minWidth: normalize(42),
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(12),
    backgroundColor: COLORS.cardBackgroundDark,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  dayPillRotation: {
    minWidth: normalize(42),
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(12),
    backgroundColor: COLORS.cardBackgroundDark,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  dayPillSelected: {
    backgroundColor: COLORS.accentPrimary,
    borderColor: COLORS.accentPrimary,
    borderWidth: 1,
  },
  dayPillHasWorkout: {
    backgroundColor: COLORS.accentPrimaryFaded,
    borderColor: COLORS.accentPrimary,
    borderWidth: 1,
  },
  dayPillText: {
    fontSize: normalize(13),
    fontWeight: '600',
    color: COLORS.textMuted,
  },
  dayPillTextWeekly: {
    fontSize: normalize(14),
    fontWeight: '600',
  },
  dayPillTextRotation: {
    fontSize: normalize(12),
    fontWeight: '600',
  },
  dayPillTextSelected: {
    color: COLORS.background,
    fontWeight: '700',
  },
  dayPillTextHasWorkout: {
    color: COLORS.accentPrimary,
  },
  dayPillRestDay: {
    backgroundColor: 'transparent',
    borderColor: COLORS.border,
    borderWidth: 1,
  },
  dayPillTextRestDay: {
    color: COLORS.textMuted,
    fontWeight: '500',
  },
  dayPillContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: normalize(2),
  },
  controlButtonDisabled: {
    opacity: 0.3,
  },
  settingsButton: {
    width: normalize(42),
    height: normalize(42),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.cardBackgroundDark,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: normalize(12),
    marginLeft: normalize(8),
  },
  rotationInfo: {
    fontSize: normalize(12),
    color: COLORS.textMuted,
    fontWeight: '500',
    marginBottom: normalize(2),
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: normalize(20),
  },
  modalContent: {
    backgroundColor: COLORS.background,
    borderRadius: normalize(16),
    width: '100%',
    maxWidth: normalize(400),
    shadowColor: COLORS.shadow,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: normalize(20),
    paddingTop: normalize(20),
    paddingBottom: normalize(10),
  },
  modalTitle: {
    fontSize: normalize(18),
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  modalCloseButton: {
    padding: normalize(4),
  },
  modalBody: {
    paddingHorizontal: normalize(20),
    paddingVertical: normalize(10),
  },
  modalLabel: {
    fontSize: normalize(16),
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginBottom: normalize(12),
  },
  modalInput: {
    height: normalize(48),
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: normalize(12),
    paddingHorizontal: normalize(16),
    fontSize: normalize(16),
    color: COLORS.textPrimary,
    backgroundColor: COLORS.cardBackgroundDark,
    textAlign: 'center',
    fontWeight: '600',
  },
  modalHint: {
    fontSize: normalize(14),
    color: COLORS.textMuted,
    marginTop: normalize(8),
    textAlign: 'center',
  },
  modalFooter: {
    flexDirection: 'row',
    gap: normalize(12),
    paddingHorizontal: normalize(20),
    paddingVertical: normalize(20),
  },
  modalButtonSecondary: {
    flex: 1,
    height: normalize(48),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: normalize(12),
    backgroundColor: COLORS.cardBackgroundDark,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  modalButtonSecondaryText: {
    fontSize: normalize(16),
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  modalButtonPrimary: {
    flex: 1,
    height: normalize(48),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: normalize(12),
    backgroundColor: COLORS.accentPrimary,
  },
  modalButtonPrimaryText: {
    fontSize: normalize(16),
    fontWeight: '600',
    color: COLORS.background,
  },
  controlButton: {
    width: normalize(32),
    height: normalize(32),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.cardBackgroundDark,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: normalize(12),
    marginLeft: normalize(4),
  },
  addDayButton: {
    flex: 0,
    minWidth: normalize(45),
    paddingHorizontal: normalize(12),
    paddingVertical: normalize(10),
    borderRadius: normalize(12),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.cardBackgroundDark,
    borderColor: COLORS.border,
    borderWidth: 1,
  },
  addDayButtonText: {
    fontSize: normalize(16),
    fontWeight: '600',
    color: COLORS.accentPrimary,
  },
  contextBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: normalize(20),
    marginBottom: normalize(8),
  },
  contextText: {
    fontSize: normalize(15),
    color: COLORS.textPrimary,
    fontWeight: '500',
  },
  contextLeft: {
    flex: 1,
  },
  contextRight: {
    alignItems: 'flex-end',
  },
  contextSubtext: {
    fontSize: normalize(12),
    color: COLORS.textMuted,
    marginTop: normalize(2),
    fontStyle: 'italic',
  },
  availableCount: {
    fontSize: normalize(13),
    color: COLORS.textMuted,
    fontWeight: '500',
    flex: 1,
    textAlign: 'right',
  },
  workoutsList: {
    paddingHorizontal: normalize(20),
    gap: normalize(8),
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: normalize(60),
    paddingHorizontal: normalize(40),
  },
  emptyStateIcon: {
    alignItems: 'center',
    marginBottom: normalize(16),
  },
  emptyStateTitle: {
    fontSize: normalize(18),
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginBottom: normalize(8),
    textAlign: 'center',
  },
  emptyStateText: {
    fontSize: normalize(16),
    color: COLORS.textMuted,
    textAlign: 'center',
    marginBottom: normalize(24),
    lineHeight: normalize(22),
  },
  emptyStateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
    paddingHorizontal: normalize(20),
    paddingVertical: normalize(12),
    borderRadius: normalize(12),
    backgroundColor: COLORS.cardBackgroundDark,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  emptyStateButtonText: {
    fontSize: normalize(15),
    fontWeight: '600',
    color: COLORS.accentSecondary,
  },
});