import { StyleSheet } from 'react-native';
import { normalize } from '../../../../shared/hooks/useResponsive'

const colors = {
  background: '#02111B',
  textPrimary: '#CCC',
  inputBackground: 'rgba(30, 41, 59, 0.5)',
  inputBorder: '#2B3F50',
  inputFocused: '#4799ba',
  buttonBackground: '#FF5722',
  buttonShadow: '#FA7C00',
  errorText: '#FF6347',
  linkText: '#4799ba',
  placeholderText: '#B0B0B0',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    padding: normalize(15),
    justifyContent: 'center',
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: normalize(20),
  },
  logoText: {
    fontSize: normalize(28),
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  title: {
    fontSize: normalize(22),
    fontWeight: 'bold',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: normalize(25),
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBackground,
    borderRadius: normalize(12),
    paddingHorizontal: normalize(15),
    paddingVertical: normalize(10),
    marginBottom: normalize(15),
    width: '100%',
    borderWidth: 1,
    borderColor: colors.inputBorder,
  },
  input: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: normalize(16),
    paddingVertical: normalize(10),
  },
  inputIcon: {
    marginRight: normalize(10),
  },
  googleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#4285F4',
    borderRadius: normalize(20),
    paddingVertical: normalize(20),
    paddingHorizontal: normalize(10),
    justifyContent: 'center',
    marginTop: normalize(20),
    width: '100%',
    shadowColor: colors.buttonShadow,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  googleButtonText: {
    color: colors.textPrimary,
    fontWeight: 'bold',
    fontSize: normalize(18),
    marginLeft: normalize(10),
  },
  googleButtonIcon: {
    marginRight: normalize(10),
  },

  appleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#000',
    borderRadius: normalize(20),
    paddingVertical: normalize(20),
    paddingHorizontal: normalize(10),
    justifyContent: 'center',
    marginTop: normalize(20),
    width: '100%',
    shadowColor: colors.buttonShadow,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  appleButtonText: {
    color: colors.textPrimary,
    fontWeight: 'bold',
    fontSize: normalize(18),
    marginLeft: normalize(10),
  },
  appleButtonIcon: {
    marginRight: normalize(10),
  },
  button: {
    backgroundColor: colors.buttonBackground,
    borderRadius: normalize(20),
    paddingVertical: normalize(20),
    paddingHorizontal: normalize(10),
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    shadowColor: colors.buttonShadow,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
    marginTop: normalize(20),
  },
  buttonText: {
    color: colors.textPrimary,
    fontWeight: 'bold',
    fontSize: normalize(18),
  },
  linkText: {
    color: colors.linkText,
    fontSize: normalize(16),
    textAlign: 'center',
    marginTop: normalize(15),
  },
  error: {
    color: colors.errorText,
    textAlign: 'center',
    fontSize: normalize(14),
    marginTop: normalize(10),
  },
});

export default styles;
