import { createStyles } from '../../../../shared/theme/createStyles';
import { colors, spacing, fontSize, fontWeight, radius } from '../../../../shared/theme';

const styles = createStyles(() => ({
  container: {
    flex: 1,
    alignItems: 'center',
    padding: spacing[2],
    backgroundColor: colors.background.primary,
  },
  contentContainer: {
    width: '100%',
    flex: 1,
    alignItems: 'center',
    padding: spacing[2],
  },
  dateNavigation: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing[4],
  },
  learningStatusContainer: {
    marginTop: spacing[3],
    marginBottom: spacing[2],
    paddingHorizontal: spacing[5],
  },
  learningStatusContent: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing[2],
  },
  learningIcon: {
    marginRight: spacing[2],
  },
  learningStatusText: {
    color: colors.text.tertiary,
    fontSize: fontSize[10],
    fontWeight: fontWeight.semibold,
    textAlign: 'center',
  },
  learningProgressBar: {
    width: spacing[30],
    height: 3,
    backgroundColor: colors.background.tertiary,
    borderRadius: radius[1],
    overflow: 'hidden',
  },
  learningProgressFill: {
    height: '100%',
    backgroundColor: colors.text.tertiary,
    borderRadius: radius[1],
  },
  dateText: {
    fontSize: fontSize[22],
    fontWeight: fontWeight.extrabold,
    color: colors.text.primary,
    marginHorizontal: spacing[5],
    letterSpacing: -0.5,
  },
  statsContainer: {
    width: '100%',
    backgroundColor: colors.background.secondary,
    borderRadius: radius[5],
    alignItems: 'stretch',
    marginBottom: spacing[5],
    paddingHorizontal: spacing[8],
    paddingVertical: spacing[8],
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  metricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  leftMetricContainer: {
    alignItems: 'center',
    flex: 1,
    paddingRight: spacing[8],
    marginBottom: spacing[8],
    minHeight: spacing[25],
    justifyContent: 'center',
  },
  rightMetricContainer: {
    alignItems: 'center',
    flex: 1,
    marginBottom: spacing[8],
    paddingLeft: spacing[8],
    minHeight: spacing[25],
    justifyContent: 'center',
  },
  circularProgressContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1.2,
    paddingHorizontal: spacing[2],
    marginBottom: 5,
  },
  metricIconContainer: {
    width: spacing[10],
    height: spacing[10],
    borderRadius: radius[5],
    backgroundColor: colors.faded.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing[2],
    borderWidth: 1,
    borderColor: colors.border.primary,
  },
  stepIconContainer: {
    width: spacing[10],
    height: spacing[10],
    borderRadius: radius[5],
    backgroundColor: colors.faded.error,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing[2],
    borderWidth: 1,
    borderColor: colors.border.error,
  },
  metricValue: {
    color: colors.text.primary,
    fontSize: fontSize[16],
    fontWeight: fontWeight.extrabold,
    marginBottom: 2,
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  metricLabel: {
    color: colors.text.secondary,
    fontSize: fontSize[10],
    fontWeight: fontWeight.semibold,
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  separator: {
    marginVertical: spacing[2],
  },
  macroSection: {
    width: '100%',
  },
  macroSectionTitle: {
    color: colors.text.primary,
    fontSize: fontSize[16],
    fontWeight: fontWeight.bold,
    textAlign: 'center',
    marginBottom: spacing[4],
    letterSpacing: 0.2,
  },
  macroContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: spacing[4],
  },
  macroItem: {
    alignItems: 'center',
    flex: 1,
    marginHorizontal: spacing[1],
  },
  macroName: {
    fontSize: fontSize[14],
    color: colors.text.primary,
    fontWeight: fontWeight.bold,
    marginBottom: spacing[2],
    letterSpacing: 0.2,
  },
  macroProgressContainer: {
    position: 'relative',
    height: spacing[2],
    width: '100%',
    backgroundColor: colors.background.tertiary,
    borderRadius: radius[2],
    overflow: 'hidden',
    marginBottom: spacing[2],
  },
  macroProgressFill: {
    position: 'absolute',
    height: '100%',
    borderRadius: radius[2],
  },
  macroValues: {
    fontSize: fontSize[12],
    color: colors.text.secondary,
    fontWeight: fontWeight.semibold,
    textAlign: 'center',
  },
  learningStatus: {
    color: colors.text.secondary,
    fontSize: fontSize[12],
    textAlign: 'center',
    marginTop: spacing[2],
    marginBottom: spacing[1],
    fontWeight: fontWeight.semibold,
  },
  totalCaloriesText: {
    color: colors.text.primary,
    fontSize: fontSize[20],
    fontWeight: fontWeight.extrabold,
    textAlign: 'right',
    letterSpacing: -0.3,
  },
  mealScrollView: {
    flexGrow: 1,
  },
  foodImage: {
    width: spacing[10],
    height: spacing[10],
    borderRadius: radius[2],
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background.tertiary,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  foodContainer: {
    borderRadius: radius[4],
  },
  foodName: {
    fontSize: fontSize[14],
    fontWeight: fontWeight.semibold,
    color: colors.text.primary,
    lineHeight: 18,
    letterSpacing: 0.2,
  },
  foodCalories: {
    fontSize: fontSize[14],
    fontWeight: fontWeight.bold,
    color: colors.accent.primary,
    textAlign: 'right',
    minWidth: spacing[13],
  },
}));

export default styles;