import { StyleSheet } from 'react-native';
import { normalize } from '../../../../shared/hooks/useResponsive';

const colors = {
  bg: '#0A0E13',
  surface: '#151B23',
  surfaceLight: '#1F2937',
  primary: '#FF9500',
  primaryDark: '#E68600',
  success: '#32D74B',
  danger: '#FF453A',
  textPrimary: '#F9FAFB',
  textSecondary: '#9CA3AF',
  textTertiary: '#6B7280',
  border: 'rgba(255, 255, 255, 0.08)',
  borderLight: 'rgba(255, 255, 255, 0.05)',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    padding: normalize(8),
    backgroundColor: colors.bg,
  },
  contentContainer: {
    width: '100%',
    flex: 1,
    alignItems: 'center',
    padding: normalize(10),
  },
  dateNavigation: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: normalize(20),
  },
  learningStatusContainer: {
    marginTop: normalize(12),
    marginBottom: normalize(8),
    paddingHorizontal: normalize(20),
  },
  learningStatusContent: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: normalize(8),
  },
  learningIcon: {
    marginRight: normalize(6),
  },
  learningStatusText: {
    color: colors.textTertiary,
    fontSize: normalize(11),
    fontWeight: '600',
    textAlign: 'center',
  },
  learningProgressBar: {
    width: normalize(120),
    height: normalize(3),
    backgroundColor: colors.surfaceLight,
    borderRadius: normalize(2),
    overflow: 'hidden',
  },
  learningProgressFill: {
    height: '100%',
    backgroundColor: colors.textTertiary,
    borderRadius: normalize(2),
  },
  dateText: {
    fontSize: normalize(22),
    fontWeight: '800',
    color: colors.textPrimary,
    marginHorizontal: normalize(20),
    letterSpacing: -0.5,
  },
  statsContainer: {
    width: '100%',
    backgroundColor: colors.surface,
    borderRadius: normalize(20),
    alignItems: 'stretch',
    marginBottom: normalize(20),
    paddingHorizontal: normalize(30),
    paddingVertical: normalize(30),
    borderWidth: 1,
    borderColor: colors.border,
  },
  metricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  leftMetricContainer: {
    alignItems: 'center',
    flex: 1,
    paddingRight: normalize(30),
    marginBottom: normalize(30),
    minHeight: normalize(100),
    justifyContent: 'center',
  },
  rightMetricContainer: {
    alignItems: 'center',
    flex: 1,
    marginBottom: normalize(30),
    paddingLeft: normalize(30),
    minHeight: normalize(100),
    justifyContent: 'center',
  },
  circularProgressContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1.2,
    paddingHorizontal: normalize(10),
    marginBottom: normalize(5),
  },
  metricIconContainer: {
    width: normalize(40),
    height: normalize(40),
    borderRadius: normalize(20),
    backgroundColor: 'rgba(255, 149, 0, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: normalize(8),
    borderWidth: 1,
    borderColor: 'rgba(255, 149, 0, 0.3)',
  },
  stepIconContainer: {
    width: normalize(40),
    height: normalize(40),
    borderRadius: normalize(20),
    backgroundColor: 'rgba(50, 215, 75, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: normalize(8),
    borderWidth: 1,
    borderColor: 'rgba(50, 215, 75, 0.3)',
  },
  metricValue: {
    color: colors.textPrimary,
    fontSize: normalize(16),
    fontWeight: '800',
    marginBottom: normalize(2),
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  metricLabel: {
    color: colors.textSecondary,
    fontSize: normalize(11),
    fontWeight: '600',
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  separator: {
    marginVertical: normalize(10),
  },
  macroSection: {
    width: '100%',
  },
  macroSectionTitle: {
    color: colors.textPrimary,
    fontSize: normalize(16),
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: normalize(15),
    letterSpacing: 0.2,
  },
  macroContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: normalize(15),
  },
  macroItem: {
    alignItems: 'center',
    flex: 1,
    marginHorizontal: normalize(5),
  },
  macroName: {
    fontSize: normalize(14),
    color: colors.textPrimary,
    fontWeight: '700',
    marginBottom: normalize(10),
    letterSpacing: 0.2,
  },
  macroProgressContainer: {
    position: 'relative',
    height: normalize(8),
    width: '100%',
    backgroundColor: colors.surfaceLight,
    borderRadius: normalize(10),
    overflow: 'hidden',
    marginBottom: normalize(8),
  },
  macroProgressFill: {
    position: 'absolute',
    height: '100%',
    borderRadius: normalize(10),
  },
  macroValues: {
    fontSize: normalize(12),
    color: colors.textSecondary,
    fontWeight: '600',
    textAlign: 'center',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginTop: normalize(20),
    paddingHorizontal: normalize(10),
  },
  addButton: {
    flex: 1,
  },
  addButtonText: {
    color: colors.textPrimary,
    fontSize: normalize(20),
    fontWeight: '800',
    textAlign: 'left',
    letterSpacing: -0.3,
  },
  learningStatus: {
    color: colors.textSecondary,
    fontSize: normalize(12),
    textAlign: 'center',
    marginTop: normalize(8),
    marginBottom: normalize(4),
    fontWeight: '600',
  },
  totalCaloriesText: {
    color: colors.textPrimary,
    fontSize: normalize(20),
    fontWeight: '800',
    textAlign: 'right',
    letterSpacing: -0.3,
  },
  mealScrollView: {
    flexGrow: 1,
  },
  foodImage: {
    width: normalize(40),
    height: normalize(40),
    borderRadius: normalize(10),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.surfaceLight,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  foodContainer: {
    borderRadius: normalize(14),
  },
  foodName: {
    fontSize: normalize(14),
    fontWeight: '600',
    color: colors.textPrimary,
    lineHeight: normalize(18),
    letterSpacing: 0.2,
  },
  foodCalories: {
    fontSize: normalize(14),
    fontWeight: '700',
    color: colors.primary,
    textAlign: 'right',
    minWidth: normalize(50),
  },
});

export default styles;