import { createStyles } from '../../../../shared/theme/createStyles';
import { colors, spacing, fontSize, fontWeight, radius } from '../../../../shared/theme';

const styles = createStyles(() => ({
    container: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },

    workoutCard: {
        backgroundColor: colors.background.secondary,
        borderRadius: radius[4],
        borderWidth: 1,
        borderColor: colors.border.default,
        padding: spacing[4],
        marginBottom: spacing[3],
    },
    workoutCardTop: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing[2],
        marginBottom: spacing[2],
    },
    cardEyebrow: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.medium,
        color: colors.text.quaternary,
    },
    workoutTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: spacing[2],
    },
    workoutCardTitle: {
        fontSize: fontSize[24],
        fontWeight: fontWeight.extrabold,
        color: colors.text.primary,
        letterSpacing: -0.5,
        lineHeight: 30,
        flex: 1,
    },
    dayBadge: {
        backgroundColor: 'transparent',
        borderRadius: radius[2],
        borderWidth: 1,
        borderColor: colors.border.default,
        paddingHorizontal: spacing[2],
        paddingVertical: 3,
        marginLeft: spacing[3],
    },
    dayBadgeText: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.semibold,
        color: colors.text.secondary,
    },
    workoutMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing[2],
        marginBottom: spacing[3],
    },
    metaText: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.medium,
        color: colors.text.secondary,
    },
    metaSep: {
        fontSize: fontSize[14],
        color: colors.text.quaternary,
    },
    divider: {
        height: 1,
        backgroundColor: colors.border.default,
        marginBottom: spacing[3],
    },
    exerciseList: {
        marginBottom: spacing[3],
    },
    exerciseRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: spacing[2],
        borderBottomWidth: 1,
        borderBottomColor: colors.border.light,
        gap: spacing[2],
    },
    exerciseRowLast: {
        borderBottomWidth: 0,
    },
    exerciseSetsInline: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.bold,
        color: colors.accent.primary,
        width: spacing[6],
    },
    exerciseName: {
        flex: 1,
        fontSize: fontSize[14],
        fontWeight: fontWeight.semibold,
        color: colors.text.primary,
    },
    exerciseReps: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.medium,
        color: colors.text.secondary,
    },
    exerciseMore: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.semibold,
        color: colors.accent.primary,
        paddingTop: spacing[2],
        textAlign: 'center',
    },

    startButton: {
        backgroundColor: colors.accent.primary,
        borderRadius: radius[3],
        paddingVertical: spacing[3],
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: spacing[2],
        shadowColor: colors.accent.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 6,
    },
    startButtonDisabled: {
        backgroundColor: colors.background.tertiary,
        borderWidth: 1,
        borderColor: colors.border.default,
        shadowOpacity: 0,
        elevation: 0,
    },
    startButtonText: {
        fontSize: fontSize[16],
        fontWeight: fontWeight.bold,
        color: colors.accent.buttonText,
        letterSpacing: 0.3,
    },
    startButtonTextDisabled: {
        color: colors.text.quaternary,
    },
    resumeButton: {
        backgroundColor: colors.accent.primary,
        borderRadius: radius[3],
        paddingVertical: spacing[3],
        paddingHorizontal: spacing[4],
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: colors.accent.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 6,
    },
    resumeButtonLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing[2],
    },
    resumeButtonText: {
        fontSize: fontSize[16],
        fontWeight: fontWeight.bold,
        color: colors.accent.buttonText,
        letterSpacing: 0.3,
    },
    resumeTimer: {
        fontSize: fontSize[16],
        fontWeight: fontWeight.bold,
        color: colors.accent.buttonText,
        letterSpacing: -0.3,
    },
    pulseDot: {
        width: spacing[2],
        height: spacing[2],
        borderRadius: radius[5],
        backgroundColor: colors.accent.buttonText,
    },

    card: {
        backgroundColor: colors.background.secondary,
        borderRadius: radius[4],
        borderWidth: 1,
        borderColor: colors.border.default,
        padding: spacing[4],
        marginBottom: spacing[3],
    },
    cardRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: spacing[3],
    },
    cardTitle: {
        fontSize: fontSize[18],
        fontWeight: fontWeight.bold,
        color: colors.text.primary,
        letterSpacing: 0.2,
    },
    cardTitleRight: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.semibold,
        color: colors.accent.primary,
    },

    weekRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    weekCol: {
        alignItems: 'center',
        gap: spacing[1],
    },
    dayCircle: {
        width: spacing[9],
        height: spacing[9],
        borderRadius: radius[5],
        alignItems: 'center',
        justifyContent: 'center',
    },
    dayCircleDone: {
        backgroundColor: colors.accent.primary,
    },
    dayCircleToday: {
        backgroundColor: 'transparent',
        borderWidth: 1.5,
        borderColor: colors.accent.primary,
    },
    dayCircleWorkout: {
        backgroundColor: colors.faded.surfaceMedium,
        borderWidth: 1,
        borderColor: colors.border.default,
    },
    dayCircleRest: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: colors.border.default,
    },
    dayCircleText: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.semibold,
        color: colors.text.secondary,
    },
    dayCircleTextRest: {
        color: colors.text.quaternary,
    },
    weekDayLabel: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.semibold,
        color: colors.text.quaternary,
    },
    weekDayLabelToday: {
        color: colors.accent.primary,
    },

    upcomingRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingVertical: spacing[4],
        borderBottomWidth: 1,
        borderBottomColor: colors.border.default,
        gap: spacing[3],
    },
    upcomingRowLast: {
        borderBottomWidth: 0,
        paddingBottom: 0,
    },
    upcomingDayBadge: {
        width: spacing[10],
        height: spacing[10],
        borderRadius: radius[2],
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: colors.border.default,
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'flex-start',
    },
    upcomingDayBadgeRest: {
        borderColor: colors.border.light,
    },
    upcomingDayText: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.bold,
        color: colors.text.secondary,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    upcomingDayTextRest: {
        color: colors.text.quaternary,
    },
    upcomingInfo: {
        flex: 1,
    },
    upcomingName: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.bold,
        color: colors.text.primary,
        marginBottom: 1,
        letterSpacing: -0.1,
    },
    upcomingNameRest: {
        color: colors.text.secondary,
        fontWeight: fontWeight.semibold,
    },
    upcomingDetail: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.medium,
        color: colors.text.quaternary,
        marginTop: 2,
    },
    upcomingDuration: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.medium,
        color: colors.text.secondary,
        marginTop: 2,
    },

    quickActionsRow: {
        flexDirection: 'row',
        gap: spacing[3],
    },
    quickActionButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.background.secondary,
        borderRadius: radius[3],
        borderWidth: 1,
        borderColor: colors.border.default,
        paddingVertical: spacing[3],
        gap: spacing[2],
    },
    quickActionText: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.semibold,
        color: colors.text.primary,
    },

    modalOverlay: {
        flex: 1,
        backgroundColor: colors.background.overlay,
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: colors.background.secondary,
        borderTopLeftRadius: radius[5],
        borderTopRightRadius: radius[5],
        borderWidth: 1,
        borderColor: colors.border.default,
        borderBottomWidth: 0,
        paddingHorizontal: spacing[5],
        maxHeight: '80%',
    },
    modalHandle: {
        width: spacing[9],
        height: 4,
        borderRadius: 2,
        backgroundColor: colors.border.default,
        alignSelf: 'center',
        marginVertical: spacing[3],
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingBottom: spacing[3],
        borderBottomWidth: 1,
        borderBottomColor: colors.border.default,
        marginBottom: spacing[3],
    },
    modalHeaderLeft: {
        flex: 1,
        gap: 2,
    },
    modalDayLabel: {
        fontSize: fontSize[11],
        fontWeight: fontWeight.semibold,
        color: colors.text.quaternary,
        textTransform: 'uppercase',
        letterSpacing: 0.8,
    },
    modalTitle: {
        fontSize: fontSize[22],
        fontWeight: fontWeight.extrabold,
        color: colors.text.primary,
        letterSpacing: -0.3,
    },
    modalCloseButton: {
        width: spacing[8],
        height: spacing[8],
        borderRadius: radius[2],
        backgroundColor: colors.faded.surfaceMedium,
        borderWidth: 1,
        borderColor: colors.border.default,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalStatsRow: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        paddingVertical: spacing[3],
        marginBottom: spacing[3],
        borderBottomWidth: 1,
        borderBottomColor: colors.border.default,
    },
    modalStatItem: {
        alignItems: 'center',
    },
    modalStatValue: {
        fontSize: fontSize[22],
        fontWeight: fontWeight.extrabold,
        color: colors.accent.primary,
    },
    modalStatLabel: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.semibold,
        color: colors.text.quaternary,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginTop: 2,
    },
    modalStatDivider: {
        width: 1,
        height: spacing[6],
        backgroundColor: colors.border.default,
    },
    modalExList: {
        marginBottom: spacing[4],
    },
    modalExercisesList: {
        backgroundColor: colors.faded.surfaceLight,
        borderRadius: radius[3],
        borderWidth: 1,
        borderColor: colors.border.light,
        paddingVertical: spacing[1],
    },
    modalExRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: spacing[3],
        paddingHorizontal: spacing[3],
        borderBottomWidth: 1,
        borderBottomColor: colors.border.light,
        gap: spacing[2],
    },
    modalExRowLast: {
        borderBottomWidth: 0,
    },
    modalExSets: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.bold,
        color: colors.accent.primary,
        width: spacing[5],
    },
    modalExName: {
        flex: 1,
        fontSize: fontSize[14],
        fontWeight: fontWeight.semibold,
        color: colors.text.primary,
    },
    modalExReps: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.medium,
        color: colors.text.secondary,
    },
}));

export default styles;