import { StyleSheet } from 'react-native';
import { normalize } from '../../../../shared/hooks/useResponsive';

const colors = {
  bg: '#0A0E13',
  surface: '#151B23',
  surfaceLight: '#1F2937',
  primary: '#FF9500',
  primaryDark: '#E68600',
  success: '#32D74B',
  warning: '#FF9F0A',
  purple: '#9333EA',
  cyan: '#00d4ff',
  textPrimary: '#F9FAFB',
  textSecondary: '#9CA3AF',
  textTertiary: '#6B7280',
  border: 'rgba(255, 255, 255, 0.08)',
  borderLight: 'rgba(255, 255, 255, 0.05)',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  contentWrapper: {
    flexGrow: 1,
    paddingHorizontal: normalize(12),
    paddingTop: normalize(25),
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: normalize(20),
  },
  emptyIcon: {
    marginBottom: normalize(16),
  },
  emptyTitle: {
    fontSize: normalize(22),
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: normalize(8),
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: normalize(14),
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: normalize(24),
    lineHeight: normalize(20),
  },

  headerStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: colors.surface,
    borderRadius: normalize(14),
    paddingVertical: normalize(14),
    marginBottom: normalize(20),
    marginHorizontal: normalize(2),
    borderWidth: normalize(1),
    borderColor: colors.border,
  },
  headerStatItem: {
    alignItems: 'center',
  },
  headerStatIcon: {
    marginBottom: normalize(4),
  },
  headerStatValue: {
    fontSize: normalize(16),
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: normalize(2),
  },
  headerStatLabel: {
    fontSize: normalize(11),
    color: colors.textSecondary,
    fontWeight: '500',
  },

  workoutCard: {
    backgroundColor: colors.surface,
    borderRadius: normalize(18),
    marginBottom: normalize(20),
    padding: normalize(18),
    borderWidth: normalize(1),
    borderColor: colors.border,
  },
  workoutCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: normalize(16),
  },
  workoutInfo: {
    flex: 1,
    paddingRight: normalize(14),
  },
  workoutTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
    marginBottom: normalize(12),
  },
  workoutCardTitle: {
    fontSize: normalize(20),
    fontWeight: '700',
    color: colors.textPrimary,
    lineHeight: normalize(24),
  },
  dayBadge: {
    backgroundColor: 'rgba(0, 212, 255, 0.15)',
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(4),
    borderRadius: normalize(6),
    borderWidth: normalize(1),
    borderColor: 'rgba(0, 212, 255, 0.3)',
  },
  dayBadgeText: {
    fontSize: normalize(11),
    fontWeight: '700',
    color: colors.cyan,
  },
  workoutMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: normalize(12),
  },
  metricItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(4),
  },
  metricText: {
    fontSize: normalize(12),
    color: colors.textSecondary,
    fontWeight: '500',
  },
  previewButton: {
    backgroundColor: 'rgba(0, 212, 255, 0.15)',
    borderRadius: normalize(14),
    width: normalize(42),
    height: normalize(42),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: normalize(1),
    borderColor: 'rgba(0, 212, 255, 0.3)',
  },

  exerciseGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: normalize(8),
    marginBottom: normalize(18),
  },
  exerciseGridItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: normalize(12),
    paddingVertical: normalize(8),
    paddingHorizontal: normalize(12),
    borderWidth: normalize(1),
    borderColor: colors.border,
  },
  exerciseGridText: {
    color: colors.textSecondary,
    fontSize: normalize(13),
    fontWeight: '600',
  },
  exerciseGridMore: {
    color: colors.cyan,
    fontSize: normalize(12),
    fontWeight: '600',
  },

  startButtonContainer: {
    marginTop: normalize(6),
  },
  startButton: {
    backgroundColor: colors.primary,
    borderRadius: normalize(14),
    paddingVertical: normalize(14),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: normalize(4) },
    shadowOpacity: 0.3,
    shadowRadius: normalize(8),
    elevation: normalize(6),
  },
  startButtonText: {
    color: colors.bg,
    fontSize: normalize(15),
    fontWeight: '700',
    letterSpacing: normalize(0.5),
  },
  playIcon: {
    color: colors.bg,
    marginRight: normalize(8),
  },

  restDayCard: {
    backgroundColor: colors.surface,
    borderRadius: normalize(18),
    marginBottom: normalize(20),
    padding: normalize(18),
    borderWidth: normalize(1),
    borderColor: colors.border,
  },
  restDayContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  restDayIconContainer: {
    width: normalize(56),
    height: normalize(56),
    borderRadius: normalize(28),
    backgroundColor: 'rgba(6, 182, 212, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: normalize(14),
    borderWidth: normalize(1.5),
    borderColor: 'rgba(6, 182, 212, 0.3)',
  },
  restDayText: {
    flex: 1,
  },
  restDayTitle: {
    fontSize: normalize(20),
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: normalize(4),
  },
  restDaySubtitle: {
    fontSize: normalize(13),
    color: colors.textSecondary,
    lineHeight: normalize(18),
  },

  progressCard: {
    backgroundColor: colors.surface,
    borderRadius: normalize(18),
    padding: normalize(18),
    marginBottom: normalize(20),
    borderWidth: normalize(1),
    borderColor: colors.border,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(12),
  },
  sectionTitle: {
    fontSize: normalize(17),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  progressSubtitle: {
    fontSize: normalize(13),
    color: colors.textSecondary,
    fontWeight: '500',
  },
  daysContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dayCircle: {
    width: normalize(38),
    height: normalize(38),
    borderRadius: normalize(19),
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeDayCircle: {
    backgroundColor: colors.primary,
  },
  inactiveDayCircle: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: normalize(1),
    borderColor: colors.border,
  },
  dayText: {
    fontSize: normalize(14),
    fontWeight: '600',
    color: colors.bg,
  },
  inactiveDayText: {
    color: colors.textTertiary,
  },

  mergedCard: {
    backgroundColor: colors.surface,
    borderRadius: normalize(18),
    padding: normalize(18),
    marginBottom: normalize(20),
    borderWidth: normalize(1),
    borderColor: colors.border,
  },
  sectionHeader: {
    marginBottom: normalize(14),
  },
  upcomingGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: normalize(10),
  },
  upcomingGridItem: {
    flex: 1,
    minWidth: '48%',
    maxWidth: '48%',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: normalize(14),
    padding: normalize(14),
    borderWidth: normalize(1),
    borderColor: colors.border,
    minHeight: normalize(85),
  },
  upcomingGridItemRest: {
    backgroundColor: 'rgba(6, 182, 212, 0.08)',
    borderColor: 'rgba(6, 182, 212, 0.25)',
  },
  upcomingGridHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(8),
  },
  upcomingGridDay: {
    fontSize: normalize(12),
    fontWeight: '700',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: normalize(0.5),
  },
  upcomingGridName: {
    fontSize: normalize(15),
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: normalize(4),
    lineHeight: normalize(19),
  },
  upcomingGridNameRest: {
    color: colors.cyan,
  },
  upcomingGridInfo: {
    fontSize: normalize(12),
    color: colors.textSecondary,
    fontWeight: '500',
    lineHeight: normalize(16),
  },

  quickActionsContainer: {
    flexDirection: 'row',
    gap: normalize(8),
    marginBottom: normalize(20),
  },
  quickActionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderRadius: normalize(12),
    paddingVertical: normalize(14),
    paddingHorizontal: normalize(10),
    gap: normalize(8),
    borderWidth: normalize(1),
    borderColor: colors.border,
  },
  quickActionButtonText: {
    fontSize: normalize(14),
    fontWeight: '600',
    color: colors.textPrimary,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: normalize(18),
  },
  modalContent: {
    backgroundColor: colors.surface,
    borderRadius: normalize(18),
    width: '100%',
    maxHeight: '80%',
    borderWidth: normalize(1),
    borderColor: colors.border,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: normalize(18),
    paddingBottom: normalize(14),
    borderBottomWidth: normalize(1),
    borderBottomColor: colors.borderLight,
  },
  modalTitle: {
    fontSize: normalize(19),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  modalCloseButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: normalize(12),
    width: normalize(32),
    height: normalize(32),
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalScrollView: {
    paddingHorizontal: normalize(18),
    paddingVertical: normalize(14),
  },
  modalStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    paddingVertical: normalize(16),
    marginBottom: normalize(14),
    backgroundColor: 'rgba(255, 149, 0, 0.08)',
    borderRadius: normalize(12),
    borderWidth: normalize(1),
    borderColor: 'rgba(255, 149, 0, 0.2)',
  },
  modalStatItem: {
    alignItems: 'center',
  },
modalStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    paddingVertical: normalize(12),
    marginBottom: normalize(12),
    borderBottomWidth: normalize(1),
    borderBottomColor: colors.borderLight,
},
  modalStatItem: {
      alignItems: 'center',
  },
  modalStatValue: {
      fontSize: normalize(18),
      fontWeight: '800',
      color: colors.primary,
  },
  modalStatLabel: {
      fontSize: normalize(8),
      fontWeight: '700',
      color: colors.textTertiary,
      textTransform: 'uppercase',
      letterSpacing: 1,
      marginTop: normalize(2),
  },
  modalStatDivider: {
    width: 1,
    height: normalize(25),
    backgroundColor: colors.border,
  },
  modalExercisesList: {
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: normalize(12),
    paddingVertical: normalize(6),
    borderWidth: normalize(1),
    borderColor: colors.borderLight,
  },
  modalExerciseRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: normalize(10),
    paddingHorizontal: normalize(14),
  },
  modalExerciseRowLast: {
    borderBottomWidth: 0,
  },
  modalExerciseLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: normalize(12),
  },
  startButtonDisabled: {
    backgroundColor: '#4a4d55',
    shadowOpacity: 0,
    elevation: 0,
  },
  modalStartButtonDisabled: {
    backgroundColor: '#4a4d55',
    shadowOpacity: 0,
    elevation: 0,
  },
modalExerciseSets: {
    fontSize: normalize(12),
    fontWeight: '700',
    color: colors.primary,
    marginRight: normalize(8),
  },
  modalExerciseName: {
    flex: 1,
    fontSize: normalize(13),
    fontWeight: '600',
    color: colors.textPrimary,
    letterSpacing: 0.2,
  },
  modalBestSetContainer: {
    alignItems: 'flex-end',
  },
  modalBestSetValue: {
    fontSize: normalize(12),
    fontWeight: '600',
    color: colors.textSecondary,
    letterSpacing: 0.3,
  },
  modalStartButton: {
    backgroundColor: colors.primary,
    borderRadius: normalize(14),
    paddingVertical: normalize(14),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    margin: normalize(18),
    marginTop: normalize(14),
  },
  modalStartButtonText: {
    color: colors.bg,
    fontSize: normalize(15),
    fontWeight: '700',
    letterSpacing: normalize(0.5),
  },
  compactBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1a1d24',
    paddingVertical: normalize(10),
    paddingHorizontal: normalize(14),
    borderRadius: normalize(12),
    marginBottom: normalize(12),
    borderWidth: 1,
    borderColor: '#FF9500',
  },
  bannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
  },
  pulseDot: {
    width: normalize(8),
    height: normalize(8),
    borderRadius: normalize(4),
    backgroundColor: '#FF9500',
  },
  bannerText: {
    color: '#fff',
    fontSize: normalize(13),
    fontWeight: '600',
  },
  bannerExercises: {
    color: '#999',
    fontSize: normalize(11),
  },
  bannerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
  },
  compactTimerText: {
    color: '#FF9500',
    fontSize: normalize(13),
    fontWeight: '600',
  },
});

export default styles;