import { createStyles } from '../../../../shared/theme/createStyles';
import { colors, spacing, fontSize, fontWeight, radius } from '../../../../shared/theme';

const styles = createStyles(() => ({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },

  screenTitle: {
    fontSize: fontSize[28],
    fontWeight: fontWeight.extrabold,
    color: colors.text.primary,
    letterSpacing: -0.5,
    marginBottom: spacing[4],
    marginTop: spacing[1],
    textAlign: 'center',
  },

  workoutCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: radius[4],
    marginBottom: spacing[4],
    padding: spacing[5],
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  workoutCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing[4],
  },
  workoutInfo: {
    flex: 1,
    paddingRight: spacing[3],
  },
  workoutTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    marginBottom: spacing[2],
  },
  workoutCardTitle: {
    fontSize: fontSize[24],
    fontWeight: fontWeight.extrabold,
    color: colors.text.primary,
    lineHeight: 24,
    letterSpacing: -0.5,
  },
  workoutMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[2],
  },
  metricItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[1],
  },
  metricText: {
    fontSize: fontSize[12],
    color: colors.text.secondary,
    fontWeight: fontWeight.semibold,
  },
  previewButton: {
    backgroundColor: colors.faded.surfaceMedium,
    borderRadius: radius[2],
    width: spacing[10],
    height: spacing[9],
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border.default,
  },

  exerciseGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[2],
    marginBottom: spacing[3],
  },
  exerciseGridItem: {
    backgroundColor: colors.faded.surfaceLight,
    borderRadius: radius[2],
    paddingVertical: spacing[2],
    paddingHorizontal: spacing[3],
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  exerciseGridText: {
    color: colors.text.secondary,
    fontSize: fontSize[12],
    fontWeight: fontWeight.semibold,
  },
  exerciseGridMore: {
    color: colors.accent.primary,
    fontSize: fontSize[12],
    fontWeight: fontWeight.semibold,
  },

  startButtonContainer: {
    marginTop: spacing[3],
  },
  startButton: {
    backgroundColor: colors.accent.primary,
    borderRadius: radius[3],
    paddingVertical: spacing[4],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    shadowColor: colors.accent.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
  },
  startButtonDisabled: {
    backgroundColor: colors.faded.surfaceMedium,
    borderWidth: 1,
    borderColor: colors.border.default,
    shadowOpacity: 0,
    elevation: 0,
  },
  startButtonText: {
    color: colors.background.primary,
    fontSize: fontSize[18],
    fontWeight: fontWeight.bold,
    letterSpacing: 0.5,
  },
  playIcon: {
    color: colors.background.primary,
    marginRight: spacing[2],
  },

  restDayCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: radius[4],
    marginBottom: spacing[4],
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  restDayContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  restDayIconContainer: {
    width: spacing[13],
    height: spacing[13],
    borderRadius: radius[3],
    backgroundColor: colors.faded.surfaceLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing[3],
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  restDayText: {
    flex: 1,
  },
  restDayTitle: {
    fontSize: fontSize[20],
    fontWeight: fontWeight.extrabold,
    color: colors.text.primary,
    marginBottom: spacing[1],
    letterSpacing: -0.5,
  },
  restDaySubtitle: {
    fontSize: fontSize[14],
    color: colors.text.secondary,
    lineHeight: 18,
    fontWeight: fontWeight.medium,
  },

  progressCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: radius[4],
    paddingVertical: spacing[4],
    paddingHorizontal: spacing[4],
    marginBottom: spacing[4],
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing[3],
  },
  sectionTitle: {
    fontSize: fontSize[18],
    fontWeight: fontWeight.bold,
    color: colors.text.primary,
    letterSpacing: 0.3,
  },
  progressSubtitle: {
    fontSize: fontSize[14],
    color: colors.accent.primary,
    fontWeight: fontWeight.semibold,
  },
  daysContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dayCircle: {
    width: spacing[10],
    height: spacing[10],
    borderRadius: radius[5],
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeDayCircle: {
    backgroundColor: colors.accent.primary,
  },
  todayDayCircle: {
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: colors.accent.primary,
  },
  inactiveDayCircle: {
    backgroundColor: colors.faded.surfaceMedium,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  dayText: {
    fontSize: fontSize[14],
    fontWeight: fontWeight.semibold,
    color: colors.background.primary,
  },
  todayDayText: {
    color: colors.accent.primary,
  },
  inactiveDayText: {
    color: colors.text.tertiary,
  },

  mergedCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: radius[4],
    paddingVertical: spacing[4],
    paddingHorizontal: spacing[4],
    marginBottom: spacing[4],
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  sectionHeader: {
    marginBottom: spacing[3],
  },
  upcomingGrid: {
    flexDirection: 'row',
    gap: spacing[2],
  },
  upcomingGridItem: {
    flex: 1,
    borderRadius: radius[3],
    padding: spacing[3],
    borderWidth: 1,
    minHeight: spacing[20],
  },
  upcomingGridItemWorkout: {
    backgroundColor: colors.background.secondary,
    borderColor: colors.border.default,
  },
  upcomingGridItemRest: {
    backgroundColor: colors.faded.surfaceLight,
    borderColor: colors.border.light,
  },
  upcomingGridHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing[2],
  },
  upcomingGridDay: {
    fontSize: fontSize[10],
    fontWeight: fontWeight.bold,
    color: colors.accent.primary,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  upcomingGridDayRest: {
    color: colors.text.quaternary,
  },
  upcomingGridName: {
    fontSize: fontSize[16],
    fontWeight: fontWeight.extrabold,
    color: colors.text.primary,
    marginBottom: spacing[2],
    lineHeight: 20,
    letterSpacing: -0.3,
  },
  upcomingGridNameRest: {
    color: colors.text.tertiary,
    fontWeight: fontWeight.semibold,
  },
  upcomingGridInfoRest: {
    fontSize: fontSize[11],
    color: colors.text.quaternary,
    fontWeight: fontWeight.medium,
  },

  muscleChipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[1],
    marginTop: spacing[1],
  },
  muscleChip: {
    backgroundColor: colors.faded.surfaceLight,
    borderRadius: radius[1],
    paddingVertical: 3,
    paddingHorizontal: spacing[2],
  },
  muscleChipText: {
    fontSize: fontSize[10],
    fontWeight: fontWeight.semibold,
    color: colors.text.tertiary,
    letterSpacing: 0.2,
  },

  quickActionsContainer: {
    flexDirection: 'row',
    gap: spacing[2],
  },
  quickActionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background.secondary,
    borderRadius: radius[3],
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[1],
    gap: spacing[2],
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  quickActionButtonText: {
    fontSize: fontSize[12],
    fontWeight: fontWeight.semibold,
    color: colors.text.primary,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: colors.background.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing[5],
  },
  modalContent: {
    backgroundColor: colors.background.secondary,
    borderRadius: radius[4],
    width: '100%',
    maxHeight: '80%',
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing[4],
    paddingBottom: spacing[3],
    borderBottomWidth: 1,
    borderBottomColor: colors.border.default,
  },
  modalTitle: {
    fontSize: fontSize[20],
    fontWeight: fontWeight.bold,
    color: colors.text.primary,
  },
  modalCloseButton: {
    backgroundColor: colors.faded.surfaceMedium,
    borderRadius: radius[2],
    width: spacing[8],
    height: spacing[8],
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  modalScrollView: {
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[3],
  },
  modalStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    paddingVertical: spacing[3],
    marginBottom: spacing[3],
    borderBottomWidth: 1,
    borderBottomColor: colors.border.default,
  },
  modalStatItem: {
    alignItems: 'center',
  },
  modalStatValue: {
    fontSize: fontSize[18],
    fontWeight: fontWeight.extrabold,
    color: colors.accent.primary,
  },
  modalStatLabel: {
    fontSize: fontSize[10],
    fontWeight: fontWeight.semibold,
    color: colors.text.tertiary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: 2,
  },
  modalStatDivider: {
    width: 1,
    height: spacing[6],
    backgroundColor: colors.border.default,
  },
  modalExercisesList: {
    backgroundColor: colors.faded.surfaceLight,
    borderRadius: radius[3],
    paddingVertical: spacing[1],
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  modalExerciseRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[3],
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
  },
  modalExerciseRowLast: {
    borderBottomWidth: 0,
  },
  modalExerciseLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: spacing[3],
  },
  modalExerciseSets: {
    fontSize: fontSize[12],
    fontWeight: fontWeight.bold,
    color: colors.accent.primary,
    marginRight: spacing[2],
  },
  modalExerciseName: {
    flex: 1,
    fontSize: fontSize[14],
    fontWeight: fontWeight.semibold,
    color: colors.text.primary,
    letterSpacing: 0.2,
  },
  modalBestSetContainer: {
    alignItems: 'flex-end',
  },
  modalBestSetValue: {
    fontSize: fontSize[12],
    fontWeight: fontWeight.semibold,
    color: colors.text.secondary,
    letterSpacing: 0.3,
  },
  modalStartButton: {
    backgroundColor: colors.accent.primary,
    borderRadius: radius[3],
    paddingVertical: spacing[3],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    margin: spacing[4],
    marginTop: spacing[3],
    shadowColor: colors.accent.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
  },
  modalStartButtonDisabled: {
    backgroundColor: colors.faded.surfaceMedium,
    borderWidth: 1,
    borderColor: colors.border.default,
    shadowOpacity: 0,
    elevation: 0,
  },
  modalStartButtonText: {
    color: colors.background.primary,
    fontSize: fontSize[14],
    fontWeight: fontWeight.bold,
    letterSpacing: 0.5,
  },
  compactBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.background.secondary,
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[4],
    borderRadius: radius[3],
    marginBottom: spacing[4],
    borderWidth: 1,
    borderColor: colors.border.primary,
  },
  bannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
  },
  pulseDot: {
    width: spacing[2],
    height: spacing[2],
    borderRadius: radius[1],
    backgroundColor: colors.accent.primary,
  },
  bannerText: {
    color: colors.text.primary,
    fontSize: fontSize[14],
    fontWeight: fontWeight.semibold,
  },
  bannerExercises: {
    color: colors.text.secondary,
    fontSize: fontSize[12],
    fontWeight: fontWeight.medium,
  },
  bannerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
  },
  compactTimerText: {
    color: colors.accent.primary,
    fontSize: fontSize[14],
    fontWeight: fontWeight.bold,
  },
}));

export default styles;