import { StyleSheet } from 'react-native';
import { normalize } from '../../../../shared/hooks/useResponsive';

export const COLORS = {
  bg: '#0A0E13',
  surface: '#151B23',
  surfaceLight: 'rgba(255, 255, 255, 0.05)',
  surfaceAlpha: 'rgba(31, 41, 55, 0.5)',
  primary: '#FF9500',
  primaryDark: '#E68600',
  primaryAlpha: 'rgba(255, 149, 0, 0.3)',
  success: '#32D74B',
  warning: '#FF9F0A',
  error: '#FF4444',
  purple: '#9333EA',
  cyan: '#00d4ff',
  textPrimary: '#F9FAFB',
  textSecondary: '#9CA3AF',
  textTertiary: '#6B7280',
  textMuted: '#4B5563',
  border: 'rgba(255, 255, 255, 0.08)',
  borderLight: 'rgba(255, 255, 255, 0.05)',
  overlayDark: 'rgba(0, 0, 0, 0.8)',
  transparent: 'transparent',
  background: '#0A0E13',
  secondary: '#0A0E13',
  accentPrimary: '#FF9500',
  accentSecondary: '#00d4ff',
  accentPurple: '#9333EA',
  card: '#151B23',
  cardDark: '#1F2937',
  cardBackground: '#151B23',
  cardBackgroundDark: '#1F2937',
  textInactive: 'rgba(255, 255, 255, 0.4)',
  borderDivider: 'rgba(255, 255, 255, 0.05)',
  white: '#FFFFFF',
  shadow: 'rgba(0, 0, 0, 0.3)',
  accentPrimaryFaded: 'rgba(255, 149, 0, 0.15)',
  progressBarTrack: 'rgba(255, 255, 255, 0.1)',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  scrollView: {
    flex: 1,
  },
  contentWrapper: {
    flexGrow: 1,
    paddingHorizontal: normalize(12),
    paddingBottom: normalize(90),
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: normalize(50),
  },
  loadingText: {
    marginTop: normalize(12),
    fontSize: normalize(16),
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: normalize(20),
  },
  emptyIcon: {
    marginBottom: normalize(16),
  },
  emptyTitle: {
    fontSize: normalize(22),
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginBottom: normalize(8),
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: normalize(14),
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginBottom: normalize(24),
    lineHeight: normalize(20),
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: normalize(60),
    paddingHorizontal: normalize(32),
  },
  emptyStateTitle: {
    fontSize: normalize(18),
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginTop: normalize(16),
    marginBottom: normalize(8),
    textAlign: 'center',
  },
  emptyStateDescription: {
    fontSize: normalize(14),
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: normalize(20),
  },
  headerContainer: {
    backgroundColor: COLORS.surface,
    borderBottomWidth: normalize(1),
    borderBottomColor: COLORS.border,
    paddingVertical: normalize(20),
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: normalize(18),
    paddingTop: normalize(24),
    paddingBottom: normalize(10),
  },
  headerTitle: {
    fontSize: normalize(28),
    fontWeight: '800',
    color: COLORS.textPrimary,
    letterSpacing: normalize(-0.5),
  },
  headerCreateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: normalize(8),
    paddingHorizontal: normalize(16),
    borderRadius: normalize(12),
    backgroundColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  headerCreateButtonText: {
    color: COLORS.bg,
    fontSize: normalize(14),
    fontWeight: '700',
    marginLeft: normalize(6),
  },
  segmentedControlContainer: {
    flexDirection: 'row',
    marginHorizontal: normalize(18),
    marginBottom: normalize(0),
  },
  segmentButton: {
    flex: 0,
    paddingVertical: normalize(12),
    paddingHorizontal: normalize(15),
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    borderRadius: normalize(8),
    backgroundColor: COLORS.surfaceLight,
    marginRight: normalize(12),
    minWidth: normalize(80),
  },
  segmentButtonActive: {
    backgroundColor: COLORS.primary,
  },
  segmentButtonText: {
    color: COLORS.textSecondary,
    fontWeight: '600',
    fontSize: normalize(12),
    marginLeft: normalize(6),
  },
  segmentButtonTextActive: {
    color: COLORS.bg,
  },
  swipeContainer: {
    position: 'relative',
    marginBottom: normalize(16),
    overflow: 'visible',
  },
  deleteButtonBehind: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: normalize(90),
    backgroundColor: '#DC2626',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopRightRadius: normalize(12),
    borderBottomRightRadius: normalize(12),
  },
  deleteButtonTouch: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    gap: normalize(6),
  },
  deleteButtonText: {
    color: '#fff',
    fontSize: normalize(11),
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  workoutCard: {
    backgroundColor: COLORS.surfaceAlpha,
    borderRadius: normalize(12),
    marginBottom: normalize(16),
    padding: normalize(16),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  activeCard: {
    borderColor: COLORS.primary,
    borderWidth: 2,
  },
  activeBadgeCorner: {
    position: 'absolute',
    top: normalize(12),
    right: normalize(12),
    backgroundColor: COLORS.primary,
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(4),
    borderRadius: normalize(6),
    zIndex: 10,
  },
  activeBadgeText: {
    color: COLORS.bg,
    fontSize: normalize(10),
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  workoutCardHeader: {
    marginBottom: normalize(12),
  },
  workoutHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: normalize(12),
  },
  workoutHeaderLeft: {
    flex: 1,
    marginRight: normalize(12),
  },
  workoutMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(12),
    marginTop: normalize(6),
  },
  workoutMetrics: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(12),
    marginTop: normalize(6),
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(4),
  },
  metricItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(4),
  },
  metaItemText: {
    fontSize: normalize(12),
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
  metricText: {
    fontSize: normalize(12),
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: normalize(8),
  },
  workoutTitle: {
    fontSize: normalize(20),
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  workoutTitleLarge: {
    fontSize: normalize(19),
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginBottom: normalize(8),
  },
  categoryTagContainer: {
    alignSelf: 'flex-start',
    backgroundColor: COLORS.surfaceLight,
    borderRadius: normalize(12),
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(4),
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: normalize(12),
  },
  categoryTag: {
    fontSize: normalize(11),
    color: COLORS.textSecondary,
    fontWeight: '600',
  },
  exerciseList: {
    paddingBottom: normalize(8),
  },
  exerciseItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: normalize(6),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
  exerciseItemLast: {
    borderBottomWidth: 0,
  },
  exerciseImageContainer: {
    width: normalize(40),
    height: normalize(40),
    padding: normalize(5),
    borderRadius: normalize(10),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: normalize(16),
    borderWidth: normalize(1),
    borderColor: COLORS.borderLight,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
  },
  exerciseImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  exerciseDetails: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  exerciseInfoContainer: {
    flex: 1,
  },
  exerciseName: {
    fontSize: normalize(15),
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginBottom: normalize(4),
  },
  exerciseMuscleGroup: {
    fontSize: normalize(13),
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
  exerciseMeta: {
    alignItems: 'flex-end',
  },
  exerciseMetaSmall: {
    fontSize: normalize(12),
    color: COLORS.textMuted,
    fontWeight: '500',
    marginTop: normalize(2),
  },
  setReps: {
    fontSize: normalize(14),
    fontWeight: '500',
    color: COLORS.textSecondary,
  },
  showMore: {
    paddingVertical: normalize(5),
    alignItems: 'center',
    marginTop: normalize(8),
  },
  showMoreText: {
    fontSize: normalize(14),
    color: COLORS.cyan,
    fontWeight: '600',
  },
  workoutActions: {
    flexDirection: 'row',
    gap: normalize(10),
    paddingTop: normalize(12),
    borderTopWidth: 1,
    borderTopColor: COLORS.borderLight,
    alignItems: 'center',
  },
  editButton: {
    flex: 1,
    height: normalize(42),
    backgroundColor: COLORS.surfaceLight,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: normalize(10),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  editButtonText: {
    fontSize: normalize(14),
    fontWeight: '600',
    color: COLORS.textSecondary,
    marginLeft: normalize(6),
  },
  startButton: {
    flex: 1.5,
    height: normalize(42),
    backgroundColor: COLORS.primary,
    borderRadius: normalize(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  startButtonText: {
    color: COLORS.bg,
    fontSize: normalize(14),
    fontWeight: '700',
    marginLeft: normalize(6),
  },
  statusBarBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 50,
    backgroundColor: COLORS.surface,
    zIndex: -1,
  },
});

export default styles;