import { createStyles } from '../../../../shared/theme/createStyles';
import { colors, spacing, fontSize, fontWeight, radius } from '../../../../shared/theme';

const styles = createStyles(() => ({
    container: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    scrollView: {
        flex: 1,
    },
    contentWrapper: {
        flexGrow: 1,
        paddingHorizontal: spacing[3],
        paddingBottom: 90,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 50,
    },
    loadingText: {
        marginTop: spacing[3],
        fontSize: fontSize[16],
        color: colors.text.secondary,
        fontWeight: fontWeight.medium,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: spacing[5],
    },
    emptyIcon: {
        marginBottom: spacing[4],
    },
    emptyTitle: {
        fontSize: fontSize[22],
        fontWeight: fontWeight.bold,
        color: colors.text.primary,
        marginBottom: spacing[2],
        textAlign: 'center',
    },
    emptySubtitle: {
        fontSize: fontSize[14],
        color: colors.text.secondary,
        textAlign: 'center',
        marginBottom: spacing[6],
        lineHeight: 20,
    },
    emptyStateContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: spacing[15],
        paddingHorizontal: spacing[8],
    },
    emptyStateTitle: {
        fontSize: fontSize[18],
        fontWeight: fontWeight.semibold,
        color: colors.text.primary,
        marginTop: spacing[4],
        marginBottom: spacing[2],
        textAlign: 'center',
    },
    emptyStateDescription: {
        fontSize: fontSize[14],
        color: colors.text.secondary,
        textAlign: 'center',
        lineHeight: 20,
    },
    headerContainer: {
        backgroundColor: colors.background.secondary,
        borderBottomWidth: 1,
        borderBottomColor: colors.border.default,
        paddingVertical: spacing[5],
    },
    headerTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: spacing[4],
        paddingTop: spacing[6],
        paddingBottom: spacing[2],
    },
    headerTitle: {
        fontSize: fontSize[28],
        fontWeight: fontWeight.extrabold,
        color: colors.text.primary,
        letterSpacing: -0.5,
    },
    headerCreateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: spacing[2],
        paddingHorizontal: spacing[4],
        borderRadius: radius[3],
        backgroundColor: colors.accent.primary,
        shadowColor: colors.accent.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    headerCreateButtonText: {
        color: colors.accent.buttonText,
        fontSize: fontSize[14],
        fontWeight: fontWeight.bold,
        marginLeft: spacing[1],
    },
    segmentedControlContainer: {
        flexDirection: 'row',
        marginHorizontal: spacing[4],
        marginBottom: 0,
    },
    segmentButton: {
        flex: 0,
        paddingVertical: spacing[3],
        paddingHorizontal: spacing[4],
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        borderRadius: radius[2],
        backgroundColor: colors.faded.surface,
        marginRight: spacing[3],
        minWidth: 80,
    },
    segmentButtonActive: {
        backgroundColor: colors.accent.primary,
    },
    segmentButtonText: {
        color: colors.text.secondary,
        fontWeight: fontWeight.semibold,
        fontSize: fontSize[12],
        marginLeft: spacing[1],
    },
    segmentButtonTextActive: {
        color: colors.accent.buttonText,
    },
    swipeContainer: {
        position: 'relative',
        marginBottom: spacing[4],
        overflow: 'visible',
    },
    deleteButtonBehind: {
        position: 'absolute',
        right: 0,
        top: 0,
        bottom: 0,
        width: 90,
        backgroundColor: colors.accent.errorDark,
        justifyContent: 'center',
        alignItems: 'center',
        borderTopRightRadius: radius[3],
        borderBottomRightRadius: radius[3],
    },
    deleteButtonTouch: {
        flex: 1,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        gap: spacing[1],
    },
    deleteButtonText: {
        color: colors.text.primary,
        fontSize: fontSize[10],
        fontWeight: fontWeight.bold,
        letterSpacing: 0.5,
    },
    workoutCard: {
        backgroundColor: colors.faded.surfaceLight,
        borderRadius: radius[3],
        marginBottom: spacing[4],
        padding: spacing[4],
        borderWidth: 1,
        borderColor: colors.border.default,
    },
    activeCard: {
        borderColor: colors.accent.primary,
        borderWidth: 2,
    },
    activeBadgeCorner: {
        position: 'absolute',
        top: spacing[3],
        right: spacing[3],
        backgroundColor: colors.accent.primary,
        paddingHorizontal: spacing[2],
        paddingVertical: spacing[1],
        borderRadius: radius[1],
        zIndex: 10,
    },
    activeBadgeText: {
        color: colors.accent.buttonText,
        fontSize: fontSize[10],
        fontWeight: fontWeight.bold,
        letterSpacing: 0.5,
    },
    workoutCardHeader: {
        marginBottom: spacing[3],
    },
    workoutHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: spacing[3],
    },
    workoutHeaderLeft: {
        flex: 1,
        marginRight: spacing[3],
    },
    workoutMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing[3],
        marginTop: spacing[1],
    },
    workoutMetrics: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing[3],
        marginTop: spacing[1],
    },
    metaItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing[1],
    },
    metricItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing[1],
    },
    metaItemText: {
        fontSize: fontSize[12],
        color: colors.text.secondary,
        fontWeight: fontWeight.medium,
    },
    metricText: {
        fontSize: fontSize[12],
        color: colors.text.secondary,
        fontWeight: fontWeight.medium,
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing[2],
    },
    workoutTitle: {
        fontSize: fontSize[20],
        fontWeight: fontWeight.bold,
        color: colors.text.primary,
    },
    workoutTitleLarge: {
        fontSize: fontSize[18],
        fontWeight: fontWeight.bold,
        color: colors.text.primary,
        marginBottom: spacing[2],
    },
    categoryTagContainer: {
        alignSelf: 'flex-start',
        backgroundColor: colors.faded.surface,
        borderRadius: radius[3],
        paddingHorizontal: spacing[2],
        paddingVertical: spacing[1],
        borderWidth: 1,
        borderColor: colors.border.default,
        marginBottom: spacing[3],
    },
    categoryTag: {
        fontSize: fontSize[10],
        color: colors.text.secondary,
        fontWeight: fontWeight.semibold,
    },
    exerciseList: {
        paddingBottom: spacing[2],
    },
    exerciseItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: spacing[1],
        borderBottomWidth: 1,
        borderBottomColor: colors.border.light,
    },
    exerciseItemLast: {
        borderBottomWidth: 0,
    },
    exerciseImageContainer: {
        width: spacing[10],
        height: spacing[10],
        padding: spacing[1],
        borderRadius: radius[2],
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: spacing[4],
        borderWidth: 1,
        borderColor: colors.border.light,
        backgroundColor: colors.faded.surfaceMedium,
    },
    exerciseImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    exerciseDetails: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    exerciseInfoContainer: {
        flex: 1,
    },
    exerciseName: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.semibold,
        color: colors.text.primary,
        marginBottom: spacing[1],
    },
    exerciseMuscleGroup: {
        fontSize: fontSize[12],
        color: colors.text.secondary,
        fontWeight: fontWeight.medium,
    },
    exerciseMeta: {
        alignItems: 'flex-end',
    },
    exerciseMetaSmall: {
        fontSize: fontSize[12],
        color: colors.text.quaternary,
        fontWeight: fontWeight.medium,
        marginTop: 2,
    },
    setReps: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.medium,
        color: colors.text.secondary,
    },
    showMore: {
        paddingVertical: spacing[1],
        alignItems: 'center',
        marginTop: spacing[2],
    },
    showMoreText: {
        fontSize: fontSize[14],
        color: colors.accent.primary,
        fontWeight: fontWeight.semibold,
    },
    workoutActions: {
        flexDirection: 'row',
        gap: spacing[2],
        paddingTop: spacing[3],
        borderTopWidth: 1,
        borderTopColor: colors.border.light,
        alignItems: 'center',
    },
    editButton: {
        flex: 1,
        height: spacing[11],
        backgroundColor: colors.faded.surface,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: radius[2],
        borderWidth: 1,
        borderColor: colors.border.default,
    },
    editButtonText: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.semibold,
        color: colors.text.secondary,
        marginLeft: spacing[1],
    },
    startButton: {
        flex: 2,
        height: spacing[11],
        backgroundColor: colors.accent.primary,
        borderRadius: radius[2],
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: spacing[1],
    },
    startButtonText: {
        color: colors.accent.buttonText,
        fontSize: fontSize[14],
        fontWeight: fontWeight.bold,
    },
    statusBarBackground: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 50,
        backgroundColor: colors.background.secondary,
        zIndex: -1,
    },
}));

export default styles;