import { StyleSheet } from 'react-native';
import { normalize } from '../../../../shared/hooks/useResponsive';

const theme = {
  background: '#02111B',
  cardBackground: 'rgba(30, 41, 59, 0.4)',
  cardBackgroundDark: 'rgba(30, 41, 59, 0.5)',
  gradientOverlay: 'rgba(255, 133, 53, 0.05)',
  textPrimary: '#FFFFFF',
  textSecondary: '#d1d5db',
  textInactive: 'rgba(255, 255, 255, 0.4)',
  textMuted: '#9ca3af',
  border: 'rgba(255, 255, 255, 0.1)',
  borderDivider: 'rgba(255, 255, 255, 0.08)',
  accentPrimary: '#ff8535',
  accentSecondary: '#00d4ff',
  accentPurple: '#a855f7',
};

export const COLORS = {
  primary: theme.accentPrimary,
  secondary: theme.background,
  accentPrimary: theme.accentPrimary,
  accentSecondary: theme.accentSecondary,
  accentPurple: theme.accentPurple,
  background: theme.background,
  card: theme.cardBackground,
  cardDark: theme.cardBackgroundDark,
  cardBackground: theme.cardBackground,
  cardBackgroundDark: theme.cardBackgroundDark,
  textPrimary: theme.textPrimary,
  textSecondary: theme.textSecondary,
  textInactive: theme.textInactive,
  textMuted: theme.textMuted,
  border: theme.border,
  borderDivider: theme.borderDivider,
  white: '#FFFFFF',
  shadow: 'rgba(0, 0, 0, 0.3)',
  success: '#10b981',
  warning: '#facc15',
  accentPrimaryFaded: 'rgba(255, 133, 53, 0.15)',
  progressBarTrack: 'rgba(255, 255, 255, 0.1)',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: normalize(18),
    paddingTop: normalize(50),
    paddingBottom: normalize(16),
    backgroundColor: theme.cardBackgroundDark,
    borderBottomWidth: normalize(1),
    borderBottomColor: theme.borderDivider,
  },
  headerContent: {
    flex: 1,
    alignItems: 'center',
  },
  greetingText: {
    fontSize: normalize(22),
    fontWeight: '700',
    color: theme.textPrimary,
    marginBottom: normalize(4),
  },
  headerSubtext: {
    fontSize: normalize(14),
    color: theme.textSecondary,
    fontWeight: '500',
  },
  settingsButton: {
    padding: normalize(10),
    borderRadius: normalize(12),
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: normalize(1),
    borderColor: theme.border,
  },
  headerStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: normalize(14),
    paddingVertical: normalize(14),
    marginBottom: normalize(20),
    marginTop: normalize(50),
    marginHorizontal: normalize(18),
    borderWidth: normalize(1),
    borderColor: theme.border,
  },
  headerStatItem: {
    alignItems: 'center',
    flex: 1,
  },
  headerStatIcon: {
    marginBottom: normalize(4),
  },
  headerStatValue: {
    fontSize: normalize(16),
    fontWeight: '700',
    color: theme.textPrimary,
    marginBottom: normalize(2),
  },
  headerStatLabel: {
    fontSize: normalize(11),
    color: theme.textSecondary,
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  segmentedControlContainer: {
    flexDirection: 'row',
    marginHorizontal: normalize(18),
    marginBottom: normalize(20),
  },
  segmentButton: {
    flex: 0,
    paddingVertical: normalize(12),
    paddingHorizontal: normalize(15),
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    borderRadius: normalize(8),
    backgroundColor: theme.cardBackgroundDark,
    marginRight: normalize(12),
    minWidth: normalize(80),
  },
  segmentButtonActive: {
    backgroundColor: theme.accentPrimary,
  },
  segmentButtonText: {
    color: theme.textSecondary,
    fontWeight: '600',
    fontSize: normalize(12),
    marginLeft: normalize(6),
  },
  segmentButtonTextActive: {
    color: theme.background,
  },
  workoutCard: {
    backgroundColor: theme.cardBackgroundDark,
    borderRadius: normalize(18),
    marginBottom: normalize(18),
    padding: normalize(18),
    borderWidth: normalize(1),
    borderColor: theme.border,
  },
  workoutHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: normalize(16),
  },
  workoutHeaderLeft: {
    flex: 1,
    marginRight: normalize(12),
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: normalize(8),
  },
  workoutTitle: {
    fontSize: normalize(20),
    fontWeight: '700',
    color: theme.textPrimary,
    lineHeight: normalize(24),
  },
  categoryTagContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: normalize(12),
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(4),
    borderWidth: normalize(1),
    borderColor: theme.border,
  },
  categoryTag: {
    fontSize: normalize(11),
    color: theme.textSecondary,
    fontWeight: '600',
  },
  workoutMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(16),
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
  },
  metaItemText: {
    fontSize: normalize(12),
    color: theme.textSecondary,
    fontWeight: '500',
  },
  exerciseList: {
    paddingBottom: normalize(8),
  },
  exerciseItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: normalize(12),
    borderBottomWidth: normalize(1),
    borderBottomColor: theme.borderDivider,
  },
  exerciseItemLast: {
    borderBottomWidth: 0,
  },
  exerciseImageContainer: {
    width: normalize(40),
    height: normalize(40),
    borderRadius: normalize(8),
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    marginRight: normalize(16),
    justifyContent: 'center',
    alignItems: 'center',
  },
  exerciseImage: {
    width: '100%',
    height: '100%',
    borderRadius: normalize(4),
  },
  exerciseDetails: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  exerciseInfoContainer: {
    flex: 1,
  },
  exerciseName: {
    fontSize: normalize(15),
    fontWeight: '600',
    color: theme.textPrimary,
    marginBottom: normalize(4),
  },
  exerciseMuscleGroup: {
    fontSize: normalize(13),
    color: theme.textSecondary,
    fontWeight: '500',
  },
  setReps: {
    fontSize: normalize(14),
    fontWeight: '500',
    color: theme.textSecondary,
  },
  showMore: {
    paddingVertical: normalize(12),
    alignItems: 'center',
    marginTop: normalize(8),
  },
  showMoreText: {
    fontSize: normalize(14),
    color: theme.accentSecondary,
    fontWeight: '600',
  },
  workoutActions: {
    flexDirection: 'row',
    paddingVertical: normalize(16),
    gap: normalize(12),
    borderTopWidth: normalize(1),
    borderTopColor: theme.borderDivider,
  },
  startButton: {
    flex: 1,
    backgroundColor: theme.accentPrimary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: normalize(14),
    paddingHorizontal: normalize(16),
    borderRadius: normalize(12),
    gap: normalize(8),
    shadowColor: theme.accentPrimary,
    shadowOffset: { width: 0, height: normalize(4) },
    shadowOpacity: 0.3,
    shadowRadius: normalize(8),
    elevation: normalize(6),
  },
  startButtonText: {
    fontSize: normalize(15),
    fontWeight: '700',
    color: theme.background,
  },
  editButton: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: normalize(16),
    borderRadius: normalize(12),
    gap: normalize(8),
    borderWidth: normalize(1),
    borderColor: theme.border,
  },
  editButtonText: {
    fontSize: normalize(15),
    fontWeight: '600',
    color: theme.textSecondary,
  },
  createButton: {
    position: 'absolute',
    bottom: normalize(30),
    right: normalize(20),
    width: normalize(56),
    height: normalize(56),
    borderRadius: normalize(28),
    backgroundColor: theme.accentPrimary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: theme.accentPrimary,
    shadowOffset: { width: 0, height: normalize(4) },
    shadowOpacity: 0.3,
    shadowRadius: normalize(8),
    elevation: normalize(8),
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: normalize(50),
  },
  loadingText: {
    marginTop: normalize(12),
    fontSize: normalize(16),
    color: theme.textSecondary,
    fontWeight: '500',
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: normalize(60),
    paddingHorizontal: normalize(32),
  },
  emptyStateTitle: {
    fontSize: normalize(18),
    fontWeight: '600',
    color: theme.textPrimary,
    marginTop: normalize(16),
    marginBottom: normalize(8),
    textAlign: 'center',
  },
  emptyStateDescription: {
    fontSize: normalize(14),
    color: theme.textSecondary,
    textAlign: 'center',
    lineHeight: normalize(20),
  },
});

export default styles;