import { StyleSheet, Dimensions } from 'react-native';
import { normalize } from '../../../../shared/hooks/useResponsive';

const { height } = Dimensions.get('window');

const colors = {
  bg: '#0A0E13',
  surface: '#151B23',
  surfaceLight: '#1F2937',
  primary: '#FF9500',
  primaryDark: '#E68600',
  success: '#32D74B',
  warning: '#FF9F0A',
  purple: '#9333EA',
  cyan: '#00d4ff',
  textPrimary: '#F9FAFB',
  textSecondary: '#9CA3AF',
  textTertiary: '#6B7280',
  border: 'rgba(255, 255, 255, 0.08)',
  borderLight: 'rgba(255, 255, 255, 0.05)',
};

export const COLORS = {
  primary: colors.primary,
  primaryDark: colors.primaryDark,
  primaryLight: '#FFBC7D',
  primaryTransparent: 'rgba(255, 149, 0, 0.15)',
  secondary: colors.bg,
  accent: '#FFFFFF',
  accent2: colors.cyan,
  accent2Transparent: 'rgba(0, 212, 255, 0.15)',
  accent2Border: 'rgba(0, 212, 255, 0.5)',
  accentPurple: colors.purple,
  background: colors.bg,
  card: colors.surface,
  cardDark: colors.surfaceLight,
  cardAlt: colors.surfaceLight,
  cardBackground: colors.surfaceLight,
  text: colors.textPrimary,
  textPrimary: colors.textPrimary,
  textSecondary: colors.textSecondary,
  textMuted: colors.textTertiary,
  textInactive: 'rgba(255, 255, 255, 0.4)',
  border: colors.border,
  borderDivider: colors.borderLight,
  borderVariations: [
    'rgba(255, 149, 0, 0.2)',
    'rgba(0, 212, 255, 0.2)',
    'rgba(168, 85, 247, 0.2)',
  ],
  divider: 'rgba(255, 255, 255, 0.05)',
  error: '#EF4444',
  success: colors.success,
  warning: '#FCD34D',
  info: '#67E8F9',
  disabled: '#374151',
  white: '#FFFFFF',
  shadow: 'rgba(0, 0, 0, 0.3)',
  progressBarTrack: 'rgba(255, 255, 255, 0.1)',
  accentPrimaryFaded: 'rgba(255, 149, 0, 0.15)',
  accentPrimary: colors.primary,
  accentSecondary: colors.cyan,
  surface: colors.surfaceLight,
  inputBackground: colors.surface,
  inputBackgroundFocused: colors.surfaceLight,
  overlay: 'rgba(10, 14, 19, 0.95)',
  borderFocused: colors.primary,
  textTertiary: 'rgba(255, 255, 255, 0.6)',
  gradient: {
    primary: [colors.primary, '#F17C12'],
    button: [colors.primary, '#FFBC7D'],
    nav: ['rgba(30, 41, 59, 0.7)', 'rgba(2, 17, 27, 0.8)'],
    border: ['rgba(255, 149, 0, 0.3)', 'rgba(0, 212, 255, 0.3)'],
  },
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  contentContainerWithButton: {
    flex: 1,
  },
  header: {
    paddingHorizontal: normalize(18),
    paddingTop: normalize(12),
    paddingBottom: normalize(12),
    backgroundColor: colors.bg,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: normalize(16),
  },
  backButton: {
    width: normalize(40),
    height: normalize(40),
    borderRadius: normalize(20),
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: normalize(1),
    borderColor: colors.border,
  },
  helpButton: {
    width: normalize(40),
    height: normalize(40),
    borderRadius: normalize(20),
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: normalize(1),
    borderColor: colors.border,
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
    marginHorizontal: normalize(12),
  },
  headerTitle: {
    fontSize: normalize(18),
    fontWeight: '700',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  headerSubtitle: {
    fontSize: normalize(13),
    color: colors.textSecondary,
    textAlign: 'center',
    fontWeight: '500',
    marginTop: normalize(2),
  },
  progressSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(10),
    marginTop: normalize(4),
  },
  progressBar: {
    flex: 1,
    height: normalize(4),
    backgroundColor: COLORS.progressBarTrack,
    borderRadius: normalize(2),
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: normalize(2),
  },
  progressText: {
    fontSize: normalize(11),
    fontWeight: '600',
    minWidth: normalize(70),
    textAlign: 'right',
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: normalize(18),
    paddingBottom: normalize(100),
  },
  formCard: {
    backgroundColor: colors.surface,
    borderRadius: normalize(18),
    padding: normalize(18),
    borderWidth: normalize(1),
    borderColor: colors.border,
  },
  fieldContainer: {
    marginBottom: normalize(18),
  },
  fieldLabel: {
    fontSize: normalize(14),
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: normalize(8),
  },
  textInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: normalize(12),
    paddingHorizontal: normalize(16),
    paddingVertical: normalize(14),
    fontSize: normalize(16),
    color: colors.textPrimary,
    borderWidth: normalize(1),
    borderColor: colors.border,
    minHeight: normalize(52),
  },
  textInputFocused: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(255, 149, 0, 0.08)',
  },
  characterCount: {
    fontSize: normalize(11),
    color: colors.textTertiary,
    marginTop: normalize(6),
    alignSelf: 'flex-end',
    fontWeight: '500',
  },
  fieldError: {
    borderColor: COLORS.error,
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: normalize(6),
    gap: normalize(4),
  },
  errorText: {
    fontSize: normalize(12),
    color: COLORS.error,
    fontWeight: '500',
  },
  pickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: normalize(12),
    paddingHorizontal: normalize(16),
    paddingVertical: normalize(14),
    borderWidth: normalize(1),
    borderColor: colors.border,
    minHeight: normalize(52),
  },
  pickerSelected: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(255, 149, 0, 0.08)',
  },
  pickerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  pickerIconContainer: {
    width: normalize(36),
    height: normalize(36),
    borderRadius: normalize(10),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: normalize(12),
    borderWidth: normalize(1),
  },
  pickerEmoji: {
    fontSize: normalize(16),
  },
  pickerText: {
    fontSize: normalize(15),
    fontWeight: '500',
    flex: 1,
  },
  pickerTextSelected: {
    color: colors.textPrimary,
  },
  placeholderText: {
    color: colors.textTertiary,
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: COLORS.overlay,
  },
  modalContainer: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    backgroundColor: colors.surface,
    borderTopLeftRadius: normalize(24),
    borderTopRightRadius: normalize(24),
    paddingHorizontal: normalize(18),
    paddingTop: normalize(8),
    paddingBottom: normalize(24),
    maxHeight: height * 0.75,
    borderWidth: normalize(1),
    borderColor: colors.border,
  },
  modalHandle: {
    width: normalize(40),
    height: normalize(4),
    backgroundColor: colors.border,
    borderRadius: normalize(2),
    alignSelf: 'center',
    marginBottom: normalize(12),
  },
  modalHeader: {
    alignItems: 'center',
    marginBottom: normalize(12),
    paddingBottom: normalize(12),
    borderBottomWidth: normalize(1),
    borderBottomColor: colors.border,
  },
  modalTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
  },
  modalTitle: {
    fontSize: normalize(17),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: normalize(12),
    paddingHorizontal: normalize(14),
    marginBottom: normalize(12),
    borderWidth: normalize(1),
    borderColor: colors.border,
    minHeight: normalize(44),
  },
  searchInput: {
    flex: 1,
    paddingVertical: normalize(10),
    paddingHorizontal: normalize(8),
    fontSize: normalize(15),
    color: colors.textPrimary,
    fontWeight: '500',
  },
  modalContent: {
    flex: 1,
  },
  menuItemWrapper: {
    marginBottom: normalize(8),
  },
  menuOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: normalize(14),
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: normalize(12),
    borderWidth: normalize(1),
    borderColor: colors.border,
    minHeight: normalize(64),
  },
  optionSelected: {
    backgroundColor: 'rgba(255, 149, 0, 0.12)',
    borderColor: colors.primary,
  },
  menuIcon: {
    width: normalize(42),
    height: normalize(42),
    borderRadius: normalize(10),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: normalize(12),
    borderWidth: normalize(1),
  },
  menuText: {
    flex: 1,
    justifyContent: 'center',
  },
  menuLabel: {
    fontSize: normalize(15),
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: normalize(2),
  },
  optionNameSelected: {
    color: colors.primary,
  },
  menuSublabel: {
    fontSize: normalize(12),
    color: colors.textSecondary,
    fontWeight: '500',
  },
  checkmarkContainer: {
    marginLeft: normalize(8),
  },
  noResultsContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: normalize(40),
  },
  noResultsText: {
    fontSize: normalize(16),
    fontWeight: '600',
    color: colors.textSecondary,
    marginTop: normalize(12),
    textAlign: 'center',
  },
  noResultsSubtext: {
    fontSize: normalize(13),
    color: colors.textTertiary,
    marginTop: normalize(4),
    textAlign: 'center',
    fontWeight: '500',
  },
  summaryCard: {
    backgroundColor: 'rgba(50, 215, 75, 0.1)',
    borderRadius: normalize(14),
    padding: normalize(16),
    marginTop: normalize(12),
    borderWidth: normalize(1),
    borderColor: colors.success,
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
    marginBottom: normalize(10),
  },
  summaryTitle: {
    fontSize: normalize(16),
    fontWeight: '700',
    color: colors.success,
  },
  summaryContent: {
    gap: normalize(6),
  },
  summaryText: {
    fontSize: normalize(14),
    color: colors.textPrimary,
    fontWeight: '500',
  },
  summaryLabel: {
    fontWeight: '600',
    color: colors.textSecondary,
  },
  submitSectionFixed: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.bg,
    paddingHorizontal: normalize(18),
    paddingTop: normalize(12),
    paddingBottom: normalize(18),
    borderTopWidth: normalize(1),
    borderTopColor: colors.border,
  },
  submitButton: {
    backgroundColor: colors.primary,
    borderRadius: normalize(14),
    paddingVertical: normalize(16),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: normalize(8),
    minHeight: normalize(54),
  },
  submitButtonDisabled: {
    backgroundColor: COLORS.disabled,
    opacity: 0.6,
  },
  submitButtonLoading: {
    backgroundColor: colors.primary,
    opacity: 0.8,
  },
  submitButtonText: {
    fontSize: normalize(16),
    fontWeight: '700',
    color: colors.bg,
  },
});

export default styles;