import { createStyles } from '../../../../shared/theme/createStyles';
import { colors, spacing, fontSize, fontWeight, radius } from '../../../../shared/theme';

const styles = createStyles(() => ({
    container: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    canvas: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    backgroundImage: {
        position: 'absolute',
        top: 0, left: 0, right: 0, bottom: 0,
        width: '100%',
        height: '100%',
    },
    backgroundOverlay: {
        position: 'absolute',
        top: 0, left: 0, right: 0, bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    fullScreen: {
        flex: 1,
        paddingHorizontal: spacing[4],
        justifyContent: 'center',
    },
    shareCard: {
        backgroundColor: colors.background.secondary,
        borderRadius: radius[5],
        borderWidth: 1,
        borderColor: colors.border.default,
        overflow: 'hidden',
    },
    floatingCard: {
        position: 'absolute',
        left: '5%',
        width: '90%',
        backgroundColor: 'rgba(21, 27, 35, 0.95)',
        borderRadius: radius[5],
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.10)',
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.6,
        shadowRadius: 24,
        elevation: 12,
    },
    cardTopBar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: spacing[4],
        paddingVertical: spacing[3],
        borderBottomWidth: 1,
        borderBottomColor: colors.border.light,
    },
    cardBrandRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing[2],
    },
    cardLogo: {
        width: spacing[7],
        height: spacing[7],
        backgroundColor: colors.accent.primary,
        borderRadius: radius[1],
        alignItems: 'center',
        justifyContent: 'center',
    },
    cardLogoImage: {
        width: '100%',
        height: '100%',
    },
    cardBrandText: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.bold,
        color: colors.text.primary,
    },
    cardDateText: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.medium,
        color: colors.text.quaternary,
    },
    cardHero: {
        paddingHorizontal: spacing[4],
        paddingTop: spacing[4],
        paddingBottom: spacing[4],
        borderBottomWidth: 1,
        borderBottomColor: colors.border.light,
        alignItems: 'center',
    },
    cardCompletedLabel: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.bold,
        color: colors.accent.primary,
        letterSpacing: 1.2,
        marginBottom: spacing[1],
        textAlign: 'center',
    },
    cardWorkoutName: {
        fontSize: fontSize[28],
        fontWeight: fontWeight.bold,
        color: colors.text.primary,
        letterSpacing: -0.5,
        lineHeight: 32,
        textAlign: 'center',
        marginBottom: spacing[3],
    },
    cardStatsRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        backgroundColor: colors.background.secondary,
        borderRadius: radius[3],
        paddingVertical: spacing[3],
        alignSelf: 'stretch',
    },
    statItem: {
        alignItems: 'center',
        flex: 1,
    },
    cardStatValue: {
        fontSize: fontSize[18],
        fontWeight: fontWeight.bold,
        color: colors.text.primary,
        letterSpacing: -0.4,
    },
    cardStatLabel: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.medium,
        color: colors.text.quaternary,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        marginTop: 2,
    },
    cardStatDivider: {
        width: 1,
        alignSelf: 'stretch',
        backgroundColor: colors.border.light,
    },
    cardExercises: {
        paddingHorizontal: spacing[4],
        paddingTop: spacing[3],
        paddingBottom: spacing[3],
    },
    cardExerciseHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: spacing[2],
        paddingBottom: spacing[2],
        borderBottomWidth: 1,
        borderBottomColor: colors.border.light,
    },
    cardExerciseHeaderLabel: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.semibold,
        color: colors.text.quaternary,
        letterSpacing: 0.8,
    },
    cardExerciseRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: spacing[2],
        borderBottomWidth: 1,
        borderBottomColor: colors.border.light,
    },
    cardExerciseRowLast: {
        borderBottomWidth: 0,
    },
    cardExerciseLeft: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing[2],
        marginRight: spacing[3],
    },
    cardExerciseSets: {
        fontWeight: fontWeight.bold,
        color: colors.accent.primary,
        width: spacing[5],
    },
    cardExerciseName: {
        flex: 1,
        fontWeight: fontWeight.semibold,
        color: colors.text.primary,
    },
    cardBestSet: {
        fontWeight: fontWeight.medium,
        color: colors.text.quaternary,
    },
    cardBestSetPR: {
        color: colors.accent.primary,
        fontWeight: fontWeight.bold,
    },
    controlsContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        paddingHorizontal: spacing[4],
        paddingTop: spacing[4],
        backgroundColor: colors.background.primary,
        borderTopWidth: 1,
        borderTopColor: colors.border.default,
    },
    shareBtn: {
        backgroundColor: colors.accent.primary,
        borderRadius: radius[3],
        paddingVertical: spacing[4],
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: spacing[2],
        marginBottom: spacing[3],
    },
    shareBtnText: {
        fontSize: fontSize[16],
        fontWeight: fontWeight.bold,
        color: colors.accent.buttonText,
        letterSpacing: 0.3,
    },
    secondaryRow: {
        flexDirection: 'row',
        gap: spacing[3],
    },
    secondaryBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: spacing[3],
        backgroundColor: colors.background.secondary,
        borderRadius: radius[3],
        borderWidth: 1,
        borderColor: colors.border.default,
        gap: spacing[2],
    },
    secondaryBtnText: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.semibold,
        color: colors.text.primary,
    },
    removeBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: spacing[3],
        backgroundColor: colors.background.secondary,
        borderRadius: radius[3],
        borderWidth: 1,
        borderColor: colors.border.default,
        gap: spacing[2],
    },
    removeBtnText: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.semibold,
        color: colors.accent.error,
    },
    closeBtn: {
        position: 'absolute',
        right: spacing[4],
        zIndex: 50,
        width: spacing[10],
        height: spacing[10],
        backgroundColor: colors.background.overlay,
        borderRadius: spacing[5],
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: colors.border.default,
    },
}));

export default styles;