import { StyleSheet, Dimensions } from "react-native";
import { normalize } from "../../../../shared/hooks/useResponsive";

const { width } = Dimensions.get('window');

export const COLORS = {
  bg: '#0A0E13',
  surface: '#151B23',
  surfaceLight: 'rgba(255, 255, 255, 0.05)',
  surfaceAlpha: 'rgba(31, 41, 55, 0.5)',
  primary: '#FF9500',
  cyan: '#00d4ff',
  textPrimary: '#F9FAFB',
  textSecondary: '#9CA3AF',
  textTertiary: '#6B7280',
  border: 'rgba(255, 255, 255, 0.08)',
  borderLight: 'rgba(255, 255, 255, 0.05)',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  backgroundContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  backgroundImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  backgroundOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  backgroundGradient: {
    flex: 1,
  },
  workoutCard: {
    position: 'absolute',
    top: normalize(120),
    width: width - normalize(32),
    alignSelf: 'center',
    borderRadius: normalize(24),
    backgroundColor: COLORS.surfaceAlpha,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingBottom: normalize(20),
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  cardHeader: {
    paddingHorizontal: normalize(20),
    paddingTop: normalize(20),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brandContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
  },
  logoContainer: {
    width: normalize(34),
    height: normalize(34),
    backgroundColor: COLORS.primary,
    borderRadius: normalize(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoImage: {
    width: '100%',
    height: '100%',
  },
  brandText: {
    fontSize: normalize(14),
    fontWeight: '900',
    color: COLORS.textPrimary,
    letterSpacing: 1.5,
  },
  dayBadge: {
    backgroundColor: 'rgba(0, 212, 255, 0.15)',
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(4),
    borderRadius: normalize(8),
    borderWidth: 1,
    borderColor: 'rgba(0, 212, 255, 0.3)',
  },
  dayBadgeText: {
    fontSize: normalize(11),
    fontWeight: '700',
    color: COLORS.cyan,
    textTransform: 'uppercase',
  },
  heroSection: {
    alignItems: 'center',
    marginVertical: normalize(24),
  },
  heroTitle: {
    fontSize: normalize(34),
    fontWeight: '900',
    color: COLORS.textPrimary,
    textAlign: 'center',
    fontStyle: 'italic',
    textTransform: 'uppercase',
    lineHeight: normalize(38),
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '100%',
    marginTop: normalize(20),
  },
  statItem: {
    alignItems: 'center',
  },
  statValue: {
    fontSize: normalize(26),
    fontWeight: '800',
    color: COLORS.primary,
  },
  statLabel: {
    fontSize: normalize(10),
    fontWeight: '700',
    color: COLORS.textTertiary,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  statDivider: {
    width: 1,
    height: normalize(25),
    backgroundColor: COLORS.border,
    alignSelf: 'center',
  },
  listContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    marginHorizontal: normalize(16),
    borderRadius: normalize(16),
    paddingVertical: normalize(10),
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  exerciseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: normalize(11),
    paddingHorizontal: normalize(16),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
  exerciseRowLast: {
    borderBottomWidth: 0,
  },
  exerciseLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: normalize(12),
  },
  exerciseSets: {
    fontSize: normalize(12),
    fontWeight: '700',
    color: COLORS.primary,
    marginRight: normalize(6),
  },
  exerciseName: {
    flex: 1,
    fontSize: normalize(12),
    fontWeight: '600',
    color: COLORS.textPrimary,
    letterSpacing: 0.2,
  },
  bestSetContainer: {
    alignItems: 'flex-end',
  },
  bestSetValue: {
    fontSize: normalize(12),
    fontWeight: '600',
    color: COLORS.textSecondary,
    letterSpacing: 0.3,
  },
  bestSetValuePR: {
    color: COLORS.primary,
    fontWeight: '700',
  },
  controlsContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: normalize(20),
    backgroundColor: COLORS.bg,
    borderTopLeftRadius: normalize(24),
    borderTopRightRadius: normalize(24),
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  primaryBtn: {
    width: '100%',
    height: normalize(54),
    borderRadius: normalize(14),
    overflow: 'hidden',
    marginTop: normalize(20),
    marginBottom: normalize(12),
  },
  primaryBtnGradient: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: normalize(8),
  },
  primaryBtnText: {
    fontSize: normalize(15),
    fontWeight: '700',
    color: COLORS.bg,
  },
  secondaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: normalize(30),
    gap: normalize(10),
  },
  secondaryBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: normalize(12),
    backgroundColor: COLORS.surface,
    borderRadius: normalize(12),
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: normalize(6),
  },
  secondaryBtnActive: {
    borderColor: COLORS.primary,
    backgroundColor: 'rgba(255, 149, 0, 0.1)',
  },
  secondaryBtnText: {
    fontSize: normalize(13),
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  closeBtn: {
    position: 'absolute',
    top: normalize(50),
    right: normalize(20),
    zIndex: 50,
    width: normalize(40),
    height: normalize(40),
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: normalize(20),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
  }
});

export default styles;