import { createStyles } from '../../../../shared/theme/createStyles';
import { colors, spacing, fontSize, fontWeight, radius } from '../../../../shared/theme';

const styles = createStyles(() => ({
    container: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    backgroundContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    backgroundImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    backgroundOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    backgroundGradient: {
        flex: 1,
    },
    workoutCard: {
        position: 'absolute',
        top: spacing[30],
        width: '90%',
        alignSelf: 'center',
        borderRadius: radius[6],
        backgroundColor: 'rgba(31, 41, 55, 0.5)',
        borderWidth: 1,
        borderColor: colors.border.default,
        paddingBottom: spacing[5],
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.5,
        shadowRadius: 20,
        elevation: 10,
    },
    cardHeader: {
        paddingHorizontal: spacing[5],
        paddingTop: spacing[5],
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    brandContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing[2],
    },
    logoContainer: {
        width: spacing[9],
        height: spacing[9],
        backgroundColor: colors.accent.primary,
        borderRadius: radius[2],
        alignItems: 'center',
        justifyContent: 'center',
    },
    logoImage: {
        width: '100%',
        height: '100%',
    },
    brandText: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.black,
        color: colors.text.primary,
        letterSpacing: 1.5,
    },
    dayBadge: {
        backgroundColor: colors.faded.primary,
        paddingHorizontal: spacing[3],
        paddingVertical: spacing[1],
        borderRadius: radius[2],
        borderWidth: 1,
        borderColor: colors.border.primary,
    },
    dayBadgeText: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.bold,
        color: colors.accent.primary,
        textTransform: 'uppercase',
    },
    heroSection: {
        alignItems: 'center',
        marginVertical: spacing[6],
    },
    heroTitle: {
        fontSize: fontSize[36],
        fontWeight: fontWeight.black,
        color: colors.text.primary,
        textAlign: 'center',
        fontStyle: 'italic',
        textTransform: 'uppercase',
        lineHeight: 40,
    },
    statsRow: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        width: '100%',
        marginTop: spacing[5],
    },
    statItem: {
        alignItems: 'center',
    },
    statValue: {
        fontSize: fontSize[28],
        fontWeight: fontWeight.extrabold,
        color: colors.accent.primary,
    },
    statLabel: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.bold,
        color: colors.text.quaternary,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    statDivider: {
        width: 1,
        height: spacing[6],
        backgroundColor: colors.border.default,
        alignSelf: 'center',
    },
    exerciseListHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: spacing[5],
        paddingBottom: spacing[2],
    },
    exerciseListHeaderLabel: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.bold,
        color: colors.text.quaternary,
        letterSpacing: 1,
    },
    listContainer: {
        backgroundColor: colors.background.overlayLight,
        marginHorizontal: spacing[5],
        borderRadius: radius[4],
        paddingVertical: spacing[2],
        borderWidth: 1,
        borderColor: colors.border.light,
    },
    exerciseRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: spacing[3],
        paddingHorizontal: spacing[4],
        borderBottomWidth: 1,
        borderBottomColor: colors.border.light,
    },
    exerciseRowLast: {
        borderBottomWidth: 0,
    },
    exerciseLeft: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: spacing[3],
    },
    exerciseSets: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.bold,
        color: colors.accent.primary,
        marginRight: spacing[1],
    },
    exerciseName: {
        flex: 1,
        fontSize: fontSize[12],
        fontWeight: fontWeight.semibold,
        color: colors.text.primary,
        letterSpacing: 0.2,
    },
    bestSetContainer: {
        alignItems: 'flex-end',
    },
    bestSetValue: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.semibold,
        color: colors.text.secondary,
        letterSpacing: 0.3,
    },
    bestSetValuePR: {
        color: colors.accent.primary,
        fontWeight: fontWeight.bold,
    },
    controlsContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        paddingHorizontal: spacing[5],
        backgroundColor: colors.background.primary,
        borderTopLeftRadius: radius[6],
        borderTopRightRadius: radius[6],
        borderTopWidth: 1,
        borderTopColor: colors.border.default,
    },
    primaryBtn: {
        width: '100%',
        height: spacing[14],
        borderRadius: radius[4],
        overflow: 'hidden',
        marginTop: spacing[5],
        marginBottom: spacing[3],
    },
    primaryBtnGradient: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: spacing[2],
    },
    primaryBtnText: {
        fontSize: fontSize[16],
        fontWeight: fontWeight.bold,
        color: colors.accent.buttonText,
    },
    secondaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: spacing[8],
        gap: spacing[3],
    },
    secondaryBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: spacing[3],
        backgroundColor: colors.background.secondary,
        borderRadius: radius[3],
        borderWidth: 1,
        borderColor: colors.border.default,
        gap: spacing[1],
    },
    secondaryBtnActive: {
        borderColor: colors.accent.primary,
        backgroundColor: colors.faded.primary,
    },
    secondaryBtnText: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.semibold,
        color: colors.text.primary,
    },
    closeBtn: {
        position: 'absolute',
        top: spacing[12],
        right: spacing[5],
        zIndex: 50,
        width: spacing[10],
        height: spacing[10],
        backgroundColor: colors.background.overlay,
        borderRadius: spacing[5],
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: colors.border.default,
    },
}));

export default styles;