import { createStyles } from '../../../../shared/theme/createStyles';
import { colors, spacing, fontSize, fontWeight, radius } from '../../../../shared/theme';

const styles = createStyles(() => ({
    container: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    contentWrapper: {
        paddingHorizontal: spacing[4],
        paddingTop: spacing[3],
        paddingBottom: spacing[22],
    },
    header: {
        marginBottom: spacing[4],
    },
    heading: {
        fontSize: fontSize[28],
        fontWeight: fontWeight.bold,
        color: colors.text.primary,
        letterSpacing: -0.5,
    },
    monthDivider: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.semibold,
        color: colors.text.quaternary,
        letterSpacing: 0.4,
        marginBottom: spacing[3],
        marginTop: spacing[1],
    },
    workoutCard: {
        backgroundColor: colors.background.secondary,
        borderRadius: radius[4],
        borderWidth: 1,
        borderColor: colors.border.default,
        padding: spacing[4],
        marginBottom: spacing[5],
    },
    workoutCardDisabled: {
        opacity: 0.5,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: spacing[1],
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing[2],
        marginLeft: spacing[2],
        flexShrink: 0,
    },
    workoutTitle: {
        fontSize: fontSize[20],
        fontWeight: fontWeight.bold,
        color: colors.text.primary,
        letterSpacing: -0.5,
        flex: 1,
    },
    dateBadge: {
        backgroundColor: colors.accent.primary,
        paddingHorizontal: spacing[2],
        // paddingVertical: 1,
        borderRadius: radius[2],
    },
    dateBadgeToday: {
        backgroundColor: colors.accent.primary,
        paddingVertical: 1,
        borderWidth: 1,
        borderColor: colors.accent.primary,
        borderRadius: radius[2],
    },
    dateText: {
        paddingVertical: 1,
        fontSize: fontSize[10],
        fontWeight: fontWeight.semibold,
        color: colors.background.primary,
        letterSpacing: 0.5,
    },
    dateTextToday: {
        color: colors.background.primary,
    },
    prBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.faded.primary,
        paddingHorizontal: spacing[1],
        paddingVertical: spacing[1],
        borderRadius: radius[2],
        gap: spacing[0],
        borderWidth: 1,
        borderColor: colors.accent.primary,
    },
    prText: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.bold,
        color: colors.accent.primary,
        letterSpacing: 0.5,
    },
    statsMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing[3],
        marginBottom: spacing[4],
        marginTop: spacing[1],
    },
    statsMetaItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing[1],
    },
    statsMetaText: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.medium,
        color: colors.text.quaternary,
    },
    exerciseListHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: spacing[2],
    },
    exerciseListHeaderLabel: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.semibold,
        color: colors.text.quaternary,
        letterSpacing: 0.8,
    },
    exercisesList: {},
    exerciseRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: spacing[2],
        borderBottomWidth: 1,
        borderBottomColor: colors.border.light,
    },
    exerciseRowLast: {
        borderBottomWidth: 0,
    },
    exerciseLeft: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing[2],
        marginRight: spacing[3],
    },
    exerciseSets: {
        fontSize: fontSize[14],
        fontWeight: fontWeight.bold,
        color: colors.accent.primary,
        width: spacing[6],
    },
    exerciseName: {
        flex: 1,
        fontSize: fontSize[14],
        fontWeight: fontWeight.semibold,
        color: colors.text.primary,
    },
    bestSetContainer: {
        alignItems: 'flex-end',
    },
    bestSetValue: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.medium,
        color: colors.text.secondary,
    },
    bestSetValuePR: {
        color: colors.accent.primary,
        fontWeight: fontWeight.semibold,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: spacing[30],
        paddingHorizontal: spacing[10],
    },
    emptyIconContainer: {
        width: spacing[28],
        height: spacing[28],
        borderRadius: radius[14],
        backgroundColor: colors.faded.surface,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: spacing[6],
        borderWidth: 1,
        borderColor: colors.border.default,
    },
    emptyTitle: {
        fontSize: fontSize[18],
        fontWeight: fontWeight.bold,
        color: colors.text.primary,
        marginBottom: spacing[2],
    },
    emptySubtitle: {
        fontSize: fontSize[14],
        color: colors.text.secondary,
        textAlign: 'center',
        lineHeight: 20,
    },
}));

export default styles;