import { createStyles } from '../../../../shared/theme/createStyles';
import { colors, spacing, fontSize, fontWeight, radius } from '../../../../shared/theme';

const styles = createStyles(() => ({
    container: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    scrollView: {
        flex: 1,
    },
    contentWrapper: {
        paddingHorizontal: spacing[4],
        paddingTop: spacing[2],
        paddingBottom: 90,
    },
    heading: {
        fontSize: fontSize[32],
        fontWeight: fontWeight.black,
        color: colors.text.primary,
        marginBottom: spacing[2],
        letterSpacing: -0.5,
    },
    workoutCard: {
        backgroundColor: colors.background.secondary,
        borderRadius: radius[4],
        padding: spacing[4],
        marginBottom: spacing[5],
        borderWidth: 1,
        borderColor: colors.border.default,
    },
    workoutCardDisabled: {
        opacity: 0.5,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: spacing[3],
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing[1],
    },
    workoutTitle: {
        fontSize: fontSize[18],
        fontWeight: fontWeight.black,
        color: colors.text.primary,
        letterSpacing: -0.3,
        flex: 1,
    },
    dateBadge: {
        backgroundColor: colors.faded.primary,
        paddingHorizontal: spacing[2],
        paddingVertical: 3,
        borderRadius: radius[1],
        borderWidth: 1,
        borderColor: colors.border.primary,
    },
    dateText: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.bold,
        color: colors.accent.primary,
        letterSpacing: 0.5,
    },
    prBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 215, 0, 0.2)',
        paddingHorizontal: spacing[1],
        paddingVertical: 3,
        borderRadius: radius[1],
        gap: spacing[0],
        borderWidth: 1,
        borderColor: 'rgba(255, 215, 0, 0.4)',
    },
    prText: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.extrabold,
        color: '#FFD700',
        letterSpacing: 0.5,
    },
    statsRow: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        paddingVertical: spacing[3],
        marginBottom: spacing[3],
        borderBottomWidth: 1,
        borderBottomColor: colors.border.light,
    },
    statItem: {
        alignItems: 'center',
    },
    statValue: {
        fontSize: fontSize[18],
        fontWeight: fontWeight.extrabold,
        color: colors.accent.primary,
    },
    statLabel: {
        fontSize: fontSize[8],
        fontWeight: fontWeight.bold,
        color: colors.text.quaternary,
        letterSpacing: 1,
        marginTop: spacing[0],
    },
    statDivider: {
        width: 1,
        height: 20,
        backgroundColor: colors.border.default,
    },
    exercisesList: {
        backgroundColor: 'rgba(0, 0, 0, 0.2)',
        borderRadius: radius[3],
        paddingVertical: spacing[1],
        borderWidth: 1,
        borderColor: colors.border.light,
    },
    exerciseRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: spacing[2],
        paddingHorizontal: spacing[3],
        borderBottomWidth: 1,
        borderBottomColor: colors.border.light,
    },
    exerciseRowLast: {
        borderBottomWidth: 0,
    },
    exerciseLeft: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: spacing[3],
    },
    exerciseSets: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.bold,
        color: colors.accent.primary,
        marginRight: spacing[1],
    },
    exerciseName: {
        flex: 1,
        fontSize: fontSize[12],
        fontWeight: fontWeight.semibold,
        color: colors.text.primary,
        letterSpacing: 0.2,
    },
    bestSetContainer: {
        alignItems: 'flex-end',
    },
    bestSetValue: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.semibold,
        color: colors.text.secondary,
        letterSpacing: 0.3,
    },
    bestSetValuePR: {
        color: colors.accent.primary,
        fontWeight: fontWeight.bold,
    },
    showMoreButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: spacing[2],
        gap: spacing[1],
    },
    showMoreText: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.semibold,
        color: colors.accent.primary,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: spacing[30],
        paddingHorizontal: spacing[10],
    },
    emptyIconContainer: {
        width: spacing[28],
        height: spacing[28],
        borderRadius: radius[14],
        backgroundColor: colors.faded.surface,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: spacing[6],
        borderWidth: 2,
        borderColor: colors.border.default,
    },
    emptyTitle: {
        fontSize: fontSize[20],
        fontWeight: fontWeight.bold,
        color: colors.text.primary,
        marginBottom: spacing[2],
    },
    emptySubtitle: {
        fontSize: fontSize[14],
        color: colors.text.secondary,
        textAlign: 'center',
        lineHeight: 20,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    monthDivider: {
        fontSize: fontSize[12],
        fontWeight: fontWeight.bold,
        color: colors.text.quaternary,
        letterSpacing: 0.5,
        marginBottom: spacing[3],
        marginLeft: spacing[1],
    },
    exerciseListHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: spacing[1],
        paddingBottom: spacing[2],
    },
    exerciseListHeaderLabel: {
        fontSize: fontSize[10],
        fontWeight: fontWeight.bold,
        color: colors.text.quaternary,
        letterSpacing: 1,
    },
}));

export default styles;