import { StyleSheet } from 'react-native';
import { normalize } from '../../../../shared/hooks/useResponsive';

const colors = {
  bg: '#0A0E13',
  surface: '#151B23',
  primary: '#FF9500',
  cyan: '#00d4ff',
  textPrimary: '#F9FAFB',
  textSecondary: '#9CA3AF',
  textTertiary: '#6B7280',
  border: 'rgba(255, 255, 255, 0.08)',
  borderLight: 'rgba(255, 255, 255, 0.05)',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  scrollView: {
    flex: 1,
  },
  contentWrapper: {
    paddingHorizontal: normalize(16),
    paddingTop: normalize(8),
    paddingBottom: normalize(90),
  },
  heading: {
    fontSize: normalize(32),
    fontWeight: '900',
    color: colors.textPrimary,
    marginBottom: normalize(10),
    letterSpacing: -0.5,
  },
  workoutCard: {
    backgroundColor: colors.surface,
    borderRadius: normalize(16),
    padding: normalize(16),
    marginBottom: normalize(20),
    borderWidth: normalize(1),
    borderColor: colors.border,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(12),
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
  },
  workoutTitle: {
    fontSize: normalize(18),
    fontWeight: '900',
    color: colors.textPrimary,
    letterSpacing: -0.3,
    flex: 1,
  },
  dateBadge: {
    backgroundColor: 'rgba(0, 212, 255, 0.15)',
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(3),
    borderRadius: normalize(6),
    borderWidth: normalize(1),
    borderColor: 'rgba(0, 212, 255, 0.3)',
  },
  dateText: {
    fontSize: normalize(9),
    fontWeight: '700',
    color: colors.cyan,
    letterSpacing: 0.5,
  },
  prBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 215, 0, 0.2)',
    paddingHorizontal: normalize(5),
    paddingVertical: normalize(3),
    borderRadius: normalize(6),
    gap: normalize(2),
    borderWidth: normalize(1),
    borderColor: 'rgba(255, 215, 0, 0.4)',
  },
  prText: {
    fontSize: normalize(9),
    fontWeight: '800',
    color: '#FFD700',
    letterSpacing: 0.5,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    paddingVertical: normalize(12),
    marginBottom: normalize(12),
    borderBottomWidth: normalize(1),
    borderBottomColor: colors.borderLight,
  },
  statItem: {
    alignItems: 'center',
  },
  statValue: {
    fontSize: normalize(18),
    fontWeight: '800',
    color: colors.primary,
  },
  statLabel: {
    fontSize: normalize(8),
    fontWeight: '700',
    color: colors.textTertiary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginTop: normalize(2),
  },
  statDivider: {
    width: 1,
    height: normalize(20),
    backgroundColor: colors.border,
  },
  exercisesList: {
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: normalize(12),
    paddingVertical: normalize(6),
    borderWidth: normalize(1),
    borderColor: colors.borderLight,
  },
  exerciseRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: normalize(9),
    paddingHorizontal: normalize(12),
    borderBottomWidth: normalize(1),
    borderBottomColor: colors.borderLight,
  },
  exerciseRowLast: {
    borderBottomWidth: 0,
  },
  exerciseLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: normalize(12),
  },
  exerciseSets: {
    fontSize: normalize(11),
    fontWeight: '700',
    color: colors.primary,
    marginRight: normalize(6),
  },
  exerciseName: {
    flex: 1,
    fontSize: normalize(11),
    fontWeight: '600',
    color: colors.textPrimary,
    letterSpacing: 0.2,
  },
  bestSetContainer: {
    alignItems: 'flex-end',
  },
  bestSetValue: {
    fontSize: normalize(11),
    fontWeight: '600',
    color: colors.textSecondary,
    letterSpacing: 0.3,
  },
  bestSetValuePR: {
    color: colors.primary,
    fontWeight: '700',
  },
  showMoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: normalize(8),
    gap: normalize(4),
  },
  showMoreText: {
    fontSize: normalize(11),
    fontWeight: '600',
    color: colors.cyan,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: normalize(120),
    paddingHorizontal: normalize(40),
  },
  emptyIconContainer: {
    width: normalize(110),
    height: normalize(110),
    borderRadius: normalize(55),
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: normalize(24),
    borderWidth: normalize(2),
    borderColor: colors.border,
  },
  emptyTitle: {
    fontSize: normalize(20),
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: normalize(8),
  },
  emptySubtitle: {
    fontSize: normalize(14),
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: normalize(20),
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  monthDivider: {
    fontSize: normalize(13),
    fontWeight: '700',
    color: colors.textTertiary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: normalize(12),
    marginLeft: normalize(4),
  },
  workoutCardDisabled: {
    opacity: 0.5,
  },
});

export default styles;