import { createStyles } from '../../../../../shared/theme/createStyles';
import { colors, spacing, fontSize, fontWeight, radius } from '../../../../../shared/theme';

const styles = createStyles(() => ({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background.primary,
    paddingHorizontal: spacing[5],
  },
  emptyIcon: {
    marginBottom: spacing[4],
  },
  emptyTitle: {
    fontSize: fontSize[22],
    fontWeight: fontWeight.bold,
    color: colors.text.primary,
    marginBottom: spacing[2],
    textAlign: 'center',
  },
  startButton: {
    marginTop: spacing[5],
    paddingHorizontal: spacing[6],
    paddingVertical: spacing[3],
    borderRadius: radius[3],
    backgroundColor: colors.accent.primary,
  },
  startButtonText: {
    fontSize: fontSize[14],
    fontWeight: fontWeight.bold,
    color: colors.accent.buttonText,
  },
  header: {
    backgroundColor: colors.background.secondary,
    paddingTop: spacing[16],
    paddingBottom: spacing[4],
    borderBottomWidth: 1,
    borderBottomColor: colors.border.default,
  },
  headerContent: {
    paddingHorizontal: spacing[5],
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    width: spacing[10],
    height: spacing[10],
    borderRadius: radius[5],
    backgroundColor: colors.faded.surface,
    borderWidth: 1,
    borderColor: colors.border.default,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing[4],
  },
  headerTitleContainer: {
    flex: 1,
  },
  splitType: {
    fontSize: fontSize[10],
    fontWeight: fontWeight.semibold,
    color: colors.text.quaternary,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: spacing[1],
  },
  splitName: {
    fontSize: fontSize[22],
    fontWeight: fontWeight.extrabold,
    color: colors.text.primary,
    letterSpacing: -0.3,
  },
  headerAction: {
    width: spacing[10],
    height: spacing[10],
    borderRadius: radius[5],
    backgroundColor: colors.faded.surface,
    borderWidth: 1,
    borderColor: colors.border.default,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: spacing[4],
  },
  statsCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: radius[4],
    borderWidth: 1,
    borderColor: colors.border.default,
    paddingVertical: spacing[4],
    paddingHorizontal: spacing[3],
    marginTop: spacing[4],
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statItem: {
    alignItems: 'center',
    flex: 1,
    gap: spacing[1],
  },
  statIconCircle: {
    width: spacing[9],
    height: spacing[9],
    borderRadius: radius[5],
    justifyContent: 'center',
    alignItems: 'center',
  },
  statValue: {
    fontSize: fontSize[16],
    fontWeight: fontWeight.extrabold,
    color: colors.text.primary,
  },
  statLabel: {
    fontSize: fontSize[10],
    color: colors.text.quaternary,
    fontWeight: fontWeight.medium,
  },
  activateButton: {
    backgroundColor: colors.accent.primary,
    borderRadius: radius[3],
    paddingVertical: spacing[4],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing[2],
    marginTop: spacing[4],
    shadowColor: colors.accent.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
  },
  activateButtonText: {
    fontSize: fontSize[16],
    fontWeight: fontWeight.bold,
    color: colors.accent.buttonText,
    letterSpacing: 0.3,
  },
  activeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing[2],
    marginTop: spacing[4],
    paddingVertical: spacing[3],
    borderRadius: radius[3],
    backgroundColor: colors.faded.primaryLight,
    borderWidth: 1,
    borderColor: colors.accent.primary,
  },
  activeBadgeText: {
    fontSize: fontSize[14],
    fontWeight: fontWeight.semibold,
    color: colors.accent.primary,
  },
  scrollContainer: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: spacing[5],
    paddingTop: spacing[4],
    paddingBottom: spacing[7],
    gap: spacing[4],
  },
  workoutCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: radius[4],
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  workoutHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing[4],
  },
  workoutIconContainer: {
    width: spacing[11],
    height: spacing[11],
    borderRadius: radius[3],
    backgroundColor: colors.faded.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing[3],
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  workoutInfo: {
    flex: 1,
  },
  workoutTitle: {
    fontSize: fontSize[16],
    fontWeight: fontWeight.bold,
    color: colors.text.primary,
    marginBottom: spacing[1],
    letterSpacing: -0.1,
  },
  workoutMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
  },
  workoutMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[1],
  },
  workoutMetaText: {
    fontSize: fontSize[12],
    color: colors.text.quaternary,
    fontWeight: fontWeight.medium,
  },
  exercisesList: {
    marginBottom: spacing[4],
  },
  exerciseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing[2],
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
    gap: spacing[2],
  },
  exerciseRowLast: {
    borderBottomWidth: 0,
  },
  exerciseSetsInline: {
    fontSize: fontSize[14],
    fontWeight: fontWeight.bold,
    color: colors.accent.primary,
    width: spacing[6],
  },
  exerciseName: {
    flex: 1,
    fontSize: fontSize[14],
    fontWeight: fontWeight.semibold,
    color: colors.text.primary,
  },
  exerciseReps: {
    fontSize: fontSize[12],
    fontWeight: fontWeight.medium,
    color: colors.text.quaternary,
  },
  moreExercisesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    marginTop: spacing[2],
  },
  moreExercisesLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.border.light,
  },
  moreExercisesText: {
    fontSize: fontSize[12],
    fontWeight: fontWeight.semibold,
    color: colors.accent.primary,
  },
  startWorkoutButton: {
    backgroundColor: colors.accent.primary,
    borderRadius: radius[3],
    paddingVertical: spacing[4],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing[2],
    marginTop: spacing[4],
    shadowColor: colors.accent.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
  },
  startWorkoutText: {
    fontSize: fontSize[16],
    fontWeight: fontWeight.bold,
    color: colors.accent.buttonText,
    letterSpacing: 0.3,
  },
  restDayCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: radius[4],
    padding: spacing[6],
    borderWidth: 1,
    borderColor: colors.border.default,
    alignItems: 'center',
    justifyContent: 'center',
  },
  restDayIcon: {
    marginBottom: spacing[3],
  },
  restDayTitle: {
    fontSize: fontSize[18],
    fontWeight: fontWeight.bold,
    color: colors.text.primary,
    marginBottom: spacing[1],
  },
  restDayDescription: {
    fontSize: fontSize[12],
    color: colors.text.quaternary,
    textAlign: 'center',
  },
}));

export default styles;