import { createStyles } from '../../../../../shared/theme/createStyles';
import { colors, spacing, fontSize, fontWeight, radius } from '../../../../../shared/theme';

const styles = createStyles(() => ({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background.primary,
    paddingHorizontal: spacing[5],
  },
  emptyIcon: {
    marginBottom: spacing[4],
  },
  emptyTitle: {
    fontSize: fontSize[22],
    fontWeight: fontWeight.bold,
    color: colors.text.primary,
    marginBottom: spacing[2],
    textAlign: 'center',
  },
  startButton: {
    marginTop: spacing[5],
    paddingHorizontal: spacing[6],
    paddingVertical: spacing[3],
    borderRadius: radius[3],
    backgroundColor: colors.accent.primary,
  },
  startButtonText: {
    fontSize: fontSize[14],
    fontWeight: fontWeight.bold,
    color: colors.accent.buttonText,
  },
  header: {
    backgroundColor: colors.background.secondary,
    paddingTop: spacing[16],
    paddingBottom: spacing[4],
    borderBottomWidth: 1,
    borderBottomColor: colors.border.default,
  },
  headerContent: {
    paddingHorizontal: spacing[5],
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    width: spacing[10],
    height: spacing[10],
    borderRadius: radius[5],
    backgroundColor: colors.faded.surface,
    borderWidth: 1,
    borderColor: colors.border.default,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing[4],
  },
  headerTitleContainer: {
    flex: 1,
  },
  splitType: {
    fontSize: fontSize[10],
    fontWeight: fontWeight.semibold,
    color: colors.text.quaternary,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: spacing[1],
  },
  splitName: {
    fontSize: fontSize[22],
    fontWeight: fontWeight.extrabold,
    color: colors.text.primary,
    letterSpacing: -0.3,
  },
  headerAction: {
    width: spacing[10],
    height: spacing[10],
    borderRadius: radius[5],
    backgroundColor: colors.faded.surface,
    borderWidth: 1,
    borderColor: colors.border.default,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: spacing[4],
  },
  statsCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: radius[4],
    borderWidth: 1,
    borderColor: colors.border.default,
    paddingVertical: spacing[4],
    paddingHorizontal: spacing[3],
    marginTop: spacing[4],
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statItem: {
    alignItems: 'center',
    flex: 1,
    gap: spacing[1],
  },
  statIconCircle: {
    width: spacing[9],
    height: spacing[9],
    borderRadius: radius[5],
    justifyContent: 'center',
    alignItems: 'center',
  },
  statValue: {
    fontSize: fontSize[16],
    fontWeight: fontWeight.extrabold,
    color: colors.text.primary,
  },
  statLabel: {
    fontSize: fontSize[10],
    color: colors.text.quaternary,
    fontWeight: fontWeight.medium,
  },
  tabNavigation: {
    flexDirection: 'row',
    backgroundColor: colors.background.secondary,
    marginHorizontal: spacing[5],
    marginVertical: spacing[4],
    borderRadius: radius[3],
    padding: spacing[1],
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing[2],
    paddingHorizontal: spacing[2],
    borderRadius: radius[2],
    gap: spacing[1],
  },
  tabActive: {
    backgroundColor: colors.accent.primary,
  },
  tabText: {
    fontSize: fontSize[12],
    fontWeight: fontWeight.semibold,
    color: colors.text.quaternary,
  },
  tabTextActive: {
    color: colors.accent.buttonText,
  },
  scrollContainer: {
    flex: 1,
  },
  tabContent: {
    paddingHorizontal: spacing[5],
    paddingBottom: spacing[7],
  },
  card: {
    backgroundColor: colors.background.secondary,
    borderRadius: radius[4],
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.border.default,
    marginBottom: spacing[3],
  },
  cardTitle: {
    fontSize: fontSize[16],
    fontWeight: fontWeight.bold,
    color: colors.text.primary,
    marginBottom: spacing[3],
  },
  metricsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    paddingVertical: spacing[3],
    marginBottom: spacing[4],
    borderBottomWidth: 1,
    borderBottomColor: colors.border.default,
  },
  metricItem: {
    alignItems: 'center',
  },
  metricValue: {
    fontSize: fontSize[20],
    fontWeight: fontWeight.extrabold,
    color: colors.accent.primary,
  },
  metricLabel: {
    fontSize: fontSize[10],
    fontWeight: fontWeight.semibold,
    color: colors.text.quaternary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: spacing[1],
  },
  metricDivider: {
    width: 1,
    height: spacing[6],
    backgroundColor: colors.border.default,
  },
  chartTitle: {
    fontSize: fontSize[12],
    color: colors.text.secondary,
    fontWeight: fontWeight.semibold,
    marginBottom: spacing[3],
  },
  chartBars: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    height: spacing[16],
  },
  barCol: {
    alignItems: 'center',
    flex: 1,
    gap: spacing[1],
  },
  bar: {
    width: spacing[4],
    borderRadius: radius[1],
    backgroundColor: colors.accent.primary,
    minHeight: spacing[1],
  },
  barDim: {
    opacity: 0.35,
  },
  barLabel: {
    fontSize: fontSize[8],
    color: colors.text.quaternary,
    fontWeight: fontWeight.medium,
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing[3],
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
  },
  activityItemLast: {
    borderBottomWidth: 0,
    paddingBottom: 0,
  },
  activityIcon: {
    width: spacing[8],
    height: spacing[8],
    borderRadius: radius[5],
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing[3],
  },
  activityContent: {
    flex: 1,
  },
  activityHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing[1],
  },
  activityTitle: {
    fontSize: fontSize[14],
    fontWeight: fontWeight.semibold,
    color: colors.text.primary,
  },
  activityDate: {
    fontSize: fontSize[10],
    color: colors.text.quaternary,
  },
  activityMeta: {
    fontSize: fontSize[12],
    color: colors.text.secondary,
  },
  activateButton: {
    backgroundColor: colors.accent.primary,
    borderRadius: radius[3],
    paddingVertical: spacing[4],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing[2],
    marginTop: spacing[2],
    shadowColor: colors.accent.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
  },
  activateButtonText: {
    fontSize: fontSize[16],
    fontWeight: fontWeight.bold,
    color: colors.accent.buttonText,
    letterSpacing: 0.3,
  },
  timeSelector: {
    flexDirection: 'row',
    backgroundColor: colors.background.secondary,
    borderRadius: radius[2],
    padding: spacing[1],
    marginBottom: spacing[4],
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  timePeriodButton: {
    flex: 1,
    paddingVertical: spacing[2],
    alignItems: 'center',
    borderRadius: radius[1],
  },
  timePeriodActive: {
    backgroundColor: colors.accent.primary,
  },
  timePeriodText: {
    fontSize: fontSize[12],
    fontWeight: fontWeight.semibold,
    color: colors.text.quaternary,
  },
  timePeriodTextActive: {
    color: colors.accent.buttonText,
  },
  strengthItem: {
    marginBottom: spacing[3],
  },
  strengthHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing[1],
  },
  strengthExercise: {
    fontSize: fontSize[14],
    fontWeight: fontWeight.semibold,
    color: colors.text.primary,
  },
  strengthGain: {
    fontSize: fontSize[14],
    fontWeight: fontWeight.bold,
    color: colors.accent.primary,
  },
  progressTrack: {
    height: spacing[1],
    backgroundColor: colors.faded.surfaceMedium,
    borderRadius: radius[1],
    overflow: 'hidden',
    marginTop: spacing[1],
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.accent.primary,
    borderRadius: radius[1],
  },
  muscleProgressItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing[2],
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
  },
  muscleProgressName: {
    fontSize: fontSize[14],
    fontWeight: fontWeight.medium,
    color: colors.text.primary,
    flex: 1,
  },
  muscleProgressStats: {
    flexDirection: 'row',
    gap: spacing[4],
  },
  progressStat: {
    alignItems: 'center',
  },
  progressStatLabel: {
    fontSize: fontSize[10],
    color: colors.text.quaternary,
    marginBottom: spacing[1],
  },
  progressStatValue: {
    fontSize: fontSize[12],
    fontWeight: fontWeight.semibold,
    color: colors.accent.primary,
  },
  daySelectorContainer: {
    marginBottom: spacing[4],
  },
  daySelector: {
    paddingHorizontal: spacing[1],
    gap: spacing[3],
  },
  dayColumn: {
    alignItems: 'center',
    gap: spacing[1],
  },
  dayCircle: {
    width: spacing[10],
    height: spacing[10],
    borderRadius: radius[5],
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background.tertiary,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  dayCircleSelected: {
    backgroundColor: colors.accent.primary,
    borderColor: colors.accent.primary,
  },
  dayCircleHasWorkout: {
    backgroundColor: colors.faded.primary,
    borderColor: colors.accent.primary,
  },
  dayCircleText: {
    fontSize: fontSize[14],
    fontWeight: fontWeight.bold,
    color: colors.text.quaternary,
  },
  dayCircleTextSelected: {
    color: colors.accent.buttonText,
  },
  dayCircleTextHasWorkout: {
    color: colors.accent.primary,
  },
  dayLabel: {
    fontSize: fontSize[10],
    fontWeight: fontWeight.medium,
    color: colors.text.quaternary,
  },
  dayLabelSelected: {
    color: colors.accent.primary,
    fontWeight: fontWeight.semibold,
  },
  workoutCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: radius[4],
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  workoutHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing[4],
  },
  workoutIconContainer: {
    width: spacing[11],
    height: spacing[11],
    borderRadius: radius[3],
    backgroundColor: colors.faded.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing[3],
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  workoutInfo: {
    flex: 1,
  },
  workoutTitle: {
    fontSize: fontSize[16],
    fontWeight: fontWeight.bold,
    color: colors.text.primary,
    marginBottom: spacing[1],
    letterSpacing: -0.1,
  },
  workoutMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
  },
  workoutMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[1],
  },
  workoutMetaText: {
    fontSize: fontSize[12],
    color: colors.text.quaternary,
    fontWeight: fontWeight.medium,
  },
  exercisesList: {
    marginBottom: spacing[4],
  },
  exerciseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing[2],
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
    gap: spacing[2],
  },
  exerciseRowLast: {
    borderBottomWidth: 0,
  },
  exerciseSetsInline: {
    fontSize: fontSize[14],
    fontWeight: fontWeight.bold,
    color: colors.accent.primary,
    width: spacing[6],
  },
  exerciseName: {
    flex: 1,
    fontSize: fontSize[14],
    fontWeight: fontWeight.semibold,
    color: colors.text.primary,
  },
  exerciseReps: {
    fontSize: fontSize[12],
    fontWeight: fontWeight.medium,
    color: colors.text.quaternary,
  },
  moreExercisesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    marginTop: spacing[2],
  },
  moreExercisesLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.border.light,
  },
  moreExercisesText: {
    fontSize: fontSize[12],
    fontWeight: fontWeight.semibold,
    color: colors.accent.primary,
  },
  startWorkoutButton: {
    backgroundColor: colors.accent.primary,
    borderRadius: radius[3],
    paddingVertical: spacing[4],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing[2],
    marginTop: spacing[4],
    shadowColor: colors.accent.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
  },
  startWorkoutText: {
    fontSize: fontSize[16],
    fontWeight: fontWeight.bold,
    color: colors.accent.buttonText,
    letterSpacing: 0.3,
  },
  restDayCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: radius[4],
    padding: spacing[6],
    borderWidth: 1,
    borderColor: colors.border.default,
    alignItems: 'center',
    justifyContent: 'center',
  },
  restDayIcon: {
    marginBottom: spacing[3],
  },
  restDayTitle: {
    fontSize: fontSize[18],
    fontWeight: fontWeight.bold,
    color: colors.text.primary,
    marginBottom: spacing[1],
  },
  restDayDescription: {
    fontSize: fontSize[12],
    color: colors.text.quaternary,
    textAlign: 'center',
  },
}));

export default styles;